'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Field,date,type Row} from './shared';
import {useOperations,OperationsFeedback,operationsRead} from './operations-action';
const states:Record<string,string>={awaiting_verification:'Waiting for new-address verification',ready_for_review:'Ready for admin review',access_sync_pending:'Access policy update pending',completed:'Completed',rejected:'Not approved',cancelled:'Cancelled'};
export default function EmailChanges({member,admin=false,targetMember}:{member:Row;admin?:boolean;targetMember?:Row}){
 const [records,setRecords]=useState<Row[]>([]),[error,setError]=useState(''),[selected,setSelected]=useState(''),[secret,setSecret]=useState<Row|null>(null),[creating,setCreating]=useState(false),[nextOffset,setNextOffset]=useState<number|null>(null);
 async function load(offset=0){const j=await operationsRead({kind:admin?'emailAdmin':'email',offset:String(offset)});setRecords(old=>offset?[...old,...j.records]:j.records);setNextOffset(j.nextOffset);setError('')}
 const action=useOperations(load),disabled=action.busy||!!action.pending,r=records.find(r=>r.id===selected),active=records.find(r=>!['completed','rejected','cancelled'].includes(r.status));
 useEffect(()=>{void load().catch(e=>setError(e.message))},[admin]);
 async function send(b:Row){const j=await action.send(b);if(j?.code)setSecret(j);return j}
 return <section className="panel email-changes">
 <div className="section-title"><div><h2>{admin?'Email access requests':'Sign-in email'}</h2><p className="fine">{admin?'Verify the new address, review the request, then confirm the Access policy.':member.email}</p></div>{(!admin&&!member.isOwner||admin&&targetMember)?<Button variant="secondary" disabled={disabled||(!admin&&!!active)} onClick={()=>setCreating(!creating)}>Request email change</Button>:null}</div>
 {!admin?<p className="fine">Your purchases and balances stay with your account. An administrator must approve a verified address before it becomes your sign-in email.</p>:null}
 {member.isOwner&&!admin?<p className="fine">The owner email is managed with the deployment’s owner setting and Access policy to protect account ownership.</p>:null}
 {creating?<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send({action:admin?'emailAdminRequest':'emailRequest',memberId:targetMember?.id,email:f.get('email'),confirmEmail:f.get('confirmEmail'),password:f.get('password')}))setCreating(false)}}><fieldset disabled={disabled}><div className="form-grid"><Field label="New email" name="email" type="email" maxLength={200} required/><Field label="Confirm new email" name="confirmEmail" type="email" maxLength={200} required/></div>{!admin?<Field label="Current password" name="password" type="password" autoComplete="current-password" maxLength={128} required/>:null}<Button type="submit">Submit request</Button></fieldset></form>:null}
 {admin&&targetMember?<p className="notice">New change request for <strong>{targetMember.name}</strong> · {targetMember.email}</p>:null}
 <OperationsFeedback action={action}/>{error?<p className="notice error" role="alert">{error}</p>:null}
 <div className="operations-list">{records.map(row=><button className="operation-row" type="button" key={row.id} onClick={()=>setSelected(row.id)}><span><strong>{row.new_email}</strong><small>{states[row.status]}</small></span><span className="fine">{date(row.created_at)}</span></button>)}</div>
 {nextOffset!=null?<Button variant="secondary" onClick={()=>load(nextOffset).catch(e=>setError(e.message))}>Load more email requests</Button>:null}
 {admin&&!records.length?<p className="empty">No email-change requests.</p>:null}
 <Dialog open={!!r} onOpenChange={o=>{if(!o&&!disabled)setSelected('')}}><DialogContent className="pilot-dialog"><DialogTitle>Email change</DialogTitle><DialogDescription>{r?states[r.status]:''}</DialogDescription>{r?<>
 <dl className="detail-pairs"><div><dt>Current email</dt><dd>{r.old_email}</dd></div><div><dt>Requested email</dt><dd>{r.new_email}</dd></div></dl>{r.note?<p className="notice">{r.note}</p>:null}
 {r.status==='awaiting_verification'?(admin?<><p>The code must be sent to <strong>{r.new_email}</strong>. Only a successful code entry from the member’s account verifies this address.</p><Button disabled={disabled} onClick={()=>send({action:'emailCode',id:r.id,version:r.version})}>{r.code_expires_at?'Replace verification code':'Create verification code'}</Button></>:<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await send({action:'emailVerify',id:r.id,version:r.version,code:f.get('code')});await load().catch(()=>{})}}><fieldset disabled={disabled}><p>The store team will send a verification code to your new address.</p><Field label="Verification code" name="code" autoComplete="one-time-code" maxLength={80} required/><Button type="submit">Verify new address</Button></fieldset></form>):null}
 {admin&&['ready_for_review','access_sync_pending','awaiting_verification'].includes(r.status)?<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await send({action:String((e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')),id:r.id,version:r.version,note:f.get('note'),identityChecked:f.get('identityChecked')==='on',newAddressAllowed:f.get('newAddressAllowed')==='on',oldAddressRemoved:f.get('oldAddressRemoved')==='on',policyRestored:f.get('policyRestored')==='on'})}}><fieldset disabled={disabled}>
 {r.status==='access_sync_pending'?<div className="policy-checklist"><p>Update the applicable Cloudflare Access policies for this member. For administrators, include the admin MFA application. Keep existing allowlist restrictions in place.</p><label className="toggle"><input type="checkbox" name="identityChecked"/>I checked the member identity and verified new address.</label><label className="toggle"><input type="checkbox" name="newAddressAllowed"/>The new email is allowed by every applicable policy.</label><label className="toggle"><input type="checkbox" name="oldAddressRemoved"/>The old email has been removed from those policies.</label><p className="fine">Completion changes the sign-in email and signs out every device. The password remains the same.</p></div>:null}
 <Field label="Decision note"><textarea name="note" required minLength={5} maxLength={1000}/></Field><div className="inline-actions">{r.status==='ready_for_review'?<Button name="decision" value="emailApprove" type="submit">Approve for policy update</Button>:null}{r.status==='access_sync_pending'?<Button name="decision" value="emailComplete" type="submit">Complete email change</Button>:null}<Button variant="secondary" name="decision" value="emailReject" type="submit">Reject request</Button></div>{r.status==='access_sync_pending'?<label className="toggle"><input name="policyRestored" type="checkbox"/>If rejecting, I restored the previous Access policy.</label>:null}
 </fieldset></form>:null}
 {!admin&&['awaiting_verification','ready_for_review'].includes(r.status)?<Button variant="ghost" disabled={disabled} onClick={()=>send({action:'emailCancel',id:r.id,version:r.version})}>Cancel request</Button>:null}<OperationsFeedback action={action}/></>:null}</DialogContent></Dialog>
 <Dialog open={!!secret} onOpenChange={o=>{if(!o)setSecret(null)}}><DialogContent className="pilot-dialog"><DialogTitle>Send the verification code</DialogTitle><DialogDescription>Send this only to the requested new email address.</DialogDescription>{secret?<><p className="code-display">{secret.code}</p><p className="fine">Expires {date(secret.expiresAt)}. The raw code is not saved; closing this window hides it.</p><Button asChild><a href={'mailto:'+encodeURIComponent(secret.email)+'?subject='+encodeURIComponent('Unit Supply email verification')+'&body='+encodeURIComponent('Your Unit Supply email-change verification code is '+secret.code+'. Enter it in My account → Sign-in email. This code expires in 24 hours. If you did not request this change, contact snackbar@iyaayasfw.com.')}>Open email draft</a></Button></>:null}</DialogContent></Dialog>
 </section>
}
