'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Plus,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {Field,money,type Row} from './shared';
export default function GearManager({p,send,open,busy,onBack,onPricing}:{p:Row;send:(b:Row)=>Promise<any>;open:(kind:string,row?:Row)=>void;busy:boolean;onBack:()=>void;onPricing:()=>void}){
 return <section className="panel gear-manager"><Button type="button" variant="ghost" onClick={onBack}><ArrowLeft size={16}/>All inventory</Button><div className="section-title"><div><span className="eyebrow">Gear management</span><h2>{p.name}</h2><p className="fine">Product details, options, and pickup instructions.</p></div><div className="inline-actions"><Button type="button" variant="outline" onClick={()=>open('product',p)}>Edit item</Button><Button type="button" variant="outline" onClick={onPricing}>Manage pricing</Button><Button type="button" variant="outline" asChild><a href={'/products/'+encodeURIComponent(p.id)}>View product</a></Button></div></div><GearDetails key={'details:'+p.id} p={p} send={send} busy={busy}/><GearOptions key={'options:'+p.id} p={p} send={send} busy={busy} open={open}/></section>
}
function GearDetails({p,send,busy}:{p:Row;send:(b:Row)=>Promise<any>;busy:boolean}){
 const [images,setImages]=useState<string[]>(p.images||[]),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 async function upload(files:FileList|null){if(!files)return;setError('');if(files.length+images.length>8){setError('Use up to eight additional images.');return}setUploading(true);try{const next=[...images];for(const file of Array.from(files)){if(file.size>5*1024*1024)throw Error('Each image must be under 5 MB.');const form=new FormData();form.set('image',file);const r=await fetch('/api/product-images',{method:'POST',body:form});const j=await r.json() as Row;if(!r.ok)throw Error(j.error);next.push(j.image);setImages([...next])}}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setUploading(false)}}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setError('');const ok=await send({action:'details',id:p.id,version:p.version,description:f.get('description'),images,personalizationLabel:f.get('label'),personalizationRequired:f.get('required')==='on',personalizationMax:Number(f.get('max')),pickupNote:f.get('pickup')});if(!ok)setError('Could not save. Review the message at the top of the page.')}
 return <details className="workbench" open><summary>Description, photos & personalization</summary><form onSubmit={save}><fieldset disabled={busy||uploading}><Field label="Product description"><textarea name="description" defaultValue={p.description} maxLength={5000} rows={5} placeholder="Materials, fit, sizing notes, ordering deadline, or other details."/></Field><div className="gallery-editor">{images.map((image,i)=><div key={image}><img src={image} alt={'Additional image '+(i+1)}/><div className="inline-actions"><Button type="button" size="sm" variant="ghost" disabled={i===0} onClick={()=>setImages(values=>{const next=[...values];[next[i-1],next[i]]=[next[i],next[i-1]];return next})}>Earlier</Button><Button type="button" size="icon" variant="ghost" aria-label={'Remove image '+(i+1)} onClick={()=>setImages(v=>v.filter(x=>x!==image))}><Trash2 size={15}/></Button></div></div>)}</div><Field label="Add detail photos (up to 8)"><Input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{upload(e.target.files);e.target.value=''}}/></Field><p className="fine">JPG, PNG, or WebP · 5 MB each. The main product image is managed in Edit item. Save details to publish these photos.</p><div className="form-grid"><Field label="Personalization field label" name="label" defaultValue={p.personalization_label} maxLength={60} placeholder="Last name, initials, or custom text"/><Field label="Maximum characters" name="max" type="number" min={1} max={80} defaultValue={p.personalization_max||30} required/></div><label className="toggle"><input type="checkbox" name="required" defaultChecked={!!p.personalization_required}/>Require personalization before adding to the bag</label><p className="fine">For name tapes, use “Last name” and require this field. Members can add different names as separate lines, each with its own quantity.</p><Field label="Pickup instructions"><textarea name="pickup" defaultValue={p.pickup_note} maxLength={500} rows={3} placeholder="Where and when members can collect their order."/></Field>{error?<p className="notice error" role="alert">{error}</p>:null}<Button type="submit">{uploading?'Uploading…':'Save product details'}</Button></fieldset></form></details>
}
function GearOptions({p,send,open,busy}:{p:Row;send:(b:Row)=>Promise<any>;open:(kind:string,row?:Row)=>void;busy:boolean}){
 const [variants,setVariants]=useState<Row[]>((p.variants||[]).map((v:Row)=>({...v,active:!!v.active,preorder:!!v.preorder}))),[sizes,setSizes]=useState('XS, S, M, L, XL, 2XL, 3XL'),[colors,setColors]=useState(''),[preset,setPreset]=useState('shirt'),[message,setMessage]=useState('');
 // Refresh saved IDs/counts without discarding drafts in the other section.
 const savedOptions=JSON.stringify(p.variants||[]);
 useEffect(()=>{const saved=JSON.parse(savedOptions) as Row[];setVariants(current=>current.map(v=>{const match=saved.find(x=>v.id?x.id===v.id:x.label===v.label);return match?{...match,...v,id:match.id,stock:match.stock,price:match.price,cost:match.cost,version:match.version}:v}))},[savedOptions]);
 const edit=(i:number,values:Row)=>setVariants(v=>v.map((row,j)=>j===i?{...row,...values}:row));
 function addPresets(){const ss=preset==='name'?[{size:'',label:'Name tape'}]:sizes.split(',').map(s=>({size:s.trim(),label:s.trim()})).filter(s=>s.label),cs=colors.split(',').map(c=>c.trim()).filter(Boolean);if(!cs.length)cs.push('');const additions=ss.flatMap(s=>cs.map(color=>({label:[preset==='hoodie'?'Hoodie':preset==='shirt'?'Shirt':s.label,preset==='name'?'':s.size,color].filter(Boolean).join(' / '),size:s.size,color,active:true,preorder:!!p.preorder}))).filter(v=>!variants.some(x=>x.label.toLowerCase()===v.label.toLowerCase()));if(variants.length+additions.length>80){setMessage('Use up to 80 options per product.');return}setVariants([...variants,...additions]);setMessage('Options added to the draft. Save options to make them available.')}
 async function save(e:React.FormEvent){e.preventDefault();setMessage('');const ok=await send({action:'variants',id:p.id,version:p.version,variants:variants.map(v=>({id:v.id,label:v.label,size:v.size,color:v.color,active:!!v.active,preorder:!!v.preorder}))});if(!ok)setMessage('Could not save. Review the message at the top of the page.')}
 return <details className="workbench" open><summary>Sizes, colors & ordering options</summary><p className="fine">New options start with zero stock and inherit the base price. Use the Pricing hub for different option prices. Keep existing options and hide those no longer offered.</p><fieldset disabled={busy}><div className="option-presets"><div className="form-grid"><Field label="Common options"><NativeSelect value={preset} onChange={e=>setPreset(e.target.value)}><option value="shirt">Shirt</option><option value="hoodie">Hoodie</option><option value="name">Name tape</option></NativeSelect></Field>{preset!=='name'?<Field label="Sizes (comma separated)" value={sizes} onChange={(e:any)=>setSizes(e.target.value)}/>:null}<Field label="Colors (optional, comma separated)" value={colors} onChange={(e:any)=>setColors(e.target.value)} placeholder="Black, Gray, Navy"/></div><div className="inline-actions"><Button type="button" variant="secondary" onClick={addPresets}>Add preset options</Button><Button type="button" variant="outline" onClick={()=>setVariants(v=>[...v,{label:'',size:'',color:'',active:true,preorder:!!p.preorder}])} disabled={variants.length>=80}><Plus size={16}/>Custom option</Button></div></div></fieldset>
 <form onSubmit={save}><fieldset disabled={busy}>{variants.map((v,i)=><div className="variant-card" key={v.id||'new'+i}><div className="form-grid"><Field label="Option name" value={v.label} maxLength={100} required onChange={(e:any)=>edit(i,{label:e.target.value})}/><Field label="Size" value={v.size} maxLength={30} onChange={(e:any)=>edit(i,{size:e.target.value})}/><Field label="Color" value={v.color} maxLength={50} onChange={(e:any)=>edit(i,{color:e.target.value})}/></div><div className="variant-controls"><label className="toggle"><input type="checkbox" checked={v.active} onChange={e=>edit(i,{active:e.target.checked})}/>Available option</label><label className="toggle"><input type="checkbox" checked={v.preorder} onChange={e=>edit(i,{preorder:e.target.checked})}/>Preorder</label><span className="fine">{v.id?(v.stock+' on hand · '+money(v.price??p.price)):'New · zero stock'}</span>{v.id?<div className="inline-actions"><Button type="button" variant="outline" size="sm" onClick={()=>open('variantStock',{...v,name:p.name,productId:p.id})}>Adjust count</Button>{!v.preorder?<Button type="button" variant="outline" size="sm" onClick={()=>open('receive',{...p,variantId:v.id,variantLabel:v.label})}>Receive stock</Button>:null}</div>:<Button type="button" variant="ghost" onClick={()=>setVariants(values=>values.filter((_,j)=>j!==i))}>Remove draft option</Button>}</div></div>)}{message?<p className="notice" role="status">{message}</p>:null}{variants.length?<Button type="submit">Save options</Button>:<p className="fine">No options yet. This product currently uses its main stock count.</p>}</fieldset></form>
 {p.variants?.length?<div className="unassigned-stock"><h3>Unassigned stock · {p.stock}</h3><p className="fine">Existing stock stays here until you allocate it to a size or color. Allocation moves units; it does not add a purchase or increase your total stock.</p><Button type="button" variant="secondary" disabled={busy||!p.stock} onClick={()=>open('allocate',p)}>Allocate existing stock</Button></div>:null}</details>
}
