'use client';
import {useEffect,useState,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Field,money,date,type Row} from './shared';
import {useOperations,OperationsFeedback,operationsRead} from './operations-action';
const states:Record<string,string>={draft:'Draft',open:'Open',kept:'Keeping it',discontinued:'Trial ended',preorder:'Preorder available',closed:'Closed'};
export function CreateInitiative({request,close,refresh}:{request:Row|null;close:()=>void;refresh:()=>Promise<unknown>}){
 const action=useOperations(refresh),disabled=action.busy||!!action.pending;
 return <Dialog open={!!request} onOpenChange={o=>{if(!o&&!disabled)close()}}><DialogContent className="pilot-dialog"><DialogTitle>Turn this request into a product</DialogTitle><DialogDescription>The title and description carry into a single draft product. Set prices, stock and options in its existing product editor.</DialogDescription>{request?<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await action.send({action:'initiativeCreate',requestIdSource:request.id,version:request.version,kind:f.get('kind'),category:f.get('category')||'Gear',endsAt:Date.parse(String(f.get('date'))+'T23:59:59Z'),note:f.get('note')}))close()}}><fieldset disabled={disabled}><h3>{request.title}</h3><Field label="Activity"><NativeSelect name="kind" defaultValue={request.shop==='gear'?'interest':'trial'}><option value="trial">Product trial</option>{request.shop==='gear'?<option value="interest">Gear interest check</option>:null}</NativeSelect></Field>{request.shop==='snacks'?<Field label="Category"><NativeSelect name="category"><option>Snacks</option><option>Drinks</option><option>Frozen</option></NativeSelect></Field>:null}<Field label="Review / interest closing date · UTC" name="date" type="date" required defaultValue={new Date(Date.now()+14*86400000).toISOString().slice(0,10)}/><Field label="Note visible to members (optional)"><textarea name="note" maxLength={1000} defaultValue="We are reviewing demand for this item."/></Field><Button type="submit">Create linked draft</Button></fieldset></form>:null}<OperationsFeedback action={action}/></DialogContent></Dialog>
}
export default function ProductInitiatives({member,admin=false,shop:providedShop,onProduct}:{member:Row;admin?:boolean;shop?:string;onProduct?:(id:string)=>void}){
 const shops=[...(member.snacks||member.role==='admin'?['snacks']:[]),...(member.gear||member.role==='admin'?['gear']:[])], [shop,setShop]=useState(providedShop||shops[0]||'gear'),[data,setData]=useState<Row>({records:[]}),[error,setError]=useState(''),[selected,setSelected]=useState('');
 const currentShop=providedShop||shop;
 const sequence=useRef(0);
 async function load(offset=0){const ticket=++sequence.current;const j=await operationsRead({kind:'initiatives',shop:currentShop,admin:String(admin),offset:String(offset)});if(ticket!==sequence.current)return;setData(old=>offset?{...j,records:[...old.records,...j.records]}:j);setError('')}
 const action=useOperations(()=>load()),disabled=action.busy||!!action.pending,r=data.records.find((x:Row)=>x.id===selected);
 useEffect(()=>{setData({records:[]});setSelected('');void load().catch(e=>setError(e.message));return()=>{sequence.current++}},[currentShop,admin]);
 if(!admin&&!data.records.length&&!error)return null;
 return <section className="initiative-section"><div className="section-title"><div><h2>{admin?'Trials & interest checks':'From your requests'}</h2><p className="fine">{admin?'Review demand, run a trial and decide what earns a place in the shop.':'Help choose what comes next.'}</p></div>{!providedShop?<Field label="Shop"><NativeSelect value={shop} onChange={e=>setShop(e.target.value)}>{shops.map(s=><option key={s} value={s}>{s==='gear'?'Unit gear':'Snack bar'}</option>)}</NativeSelect></Field>:null}</div>
 {admin?<p className="notice">Start from a member’s item request using <strong>Create trial / interest check</strong>. Its linked product stays in the regular snack or gear editor.</p>:null}
 <OperationsFeedback action={action}/>{error?<p className="notice error" role="alert">{error}</p>:null}<div className="initiative-grid">{data.records.map((i:Row)=><article className="panel initiative-card" key={i.id}><div className="section-title"><span className="eyebrow">{i.kind==='trial'?'Product trial':'Coming soon · interest check'}</span><span className={'status '+(i.state==='open'?'open':i.state==='draft'?'pending':'resolved')}>{states[i.state]}</span></div><h3>{i.name}</h3>{i.detail?<p className="fine">{i.detail}</p>:null}<p>{i.note}</p><small className="fine">{i.state==='open'&&i.ends_at<Date.now()?'Awaiting team decision · closed ':'Review date · '}{date(i.ends_at)}</small>{i.kind==='interest'?<p className="interest-total"><strong>{i.totals.members}</strong> interested members · {i.totals.quantity} items requested</p>:null}<div className="inline-actions"><Button variant="secondary" onClick={()=>setSelected(i.id)}>{admin?'Review activity':i.kind==='trial'?'Trial & feedback':'View interest check'}</Button>{i.product_id?(admin?<Button variant="ghost" onClick={()=>onProduct?.(i.product_id)}>Manage product</Button>:<a className="text-link" href={'/products/'+encodeURIComponent(i.product_id)}>{i.state==='preorder'?'Place a preorder':'View product'}</a>):null}</div></article>)}</div>{!data.records.length&&admin?<p className="empty">No product activities for this shop yet.</p>:null}{data.nextOffset!=null?<Button onClick={()=>load(data.nextOffset).catch(e=>setError(e.message))} variant="secondary">Load more activities</Button>:null}
 <Dialog open={!!selected} onOpenChange={o=>{if(!o&&!disabled)setSelected('')}}><DialogContent className="pilot-dialog task-dialog"><DialogTitle>{r?.name||'Product activity'}</DialogTitle><DialogDescription>{r?`${states[r.state]} · ${r.kind==='trial'?'Product trial':'Gear interest check'}`:''}</DialogDescription>{r?<><p>{r.note}</p><p className="fine">Review date: {date(r.ends_at)}</p>
 {!admin&&r.kind==='interest'&&r.state==='open'&&r.ends_at>Date.now()?<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await action.send({action:'interestSave',id:r.id,version:r.version,optionId:f.get('option')||'',qty:Number(f.get('qty'))})}}><fieldset disabled={disabled||!member.posting_enabled}><p className="notice">This is an interest check. It does not place an order, reserve stock or charge your account. You’ll order separately if preorders open.</p>{r.options.length?<Field label="Preferred option"><NativeSelect name="option" required><option value="">Choose an option</option>{r.options.map((v:Row)=><option key={v.id} value={v.id}>{v.label}</option>)}</NativeSelect></Field>:null}<Field label="Quantity · choose 0 to remove this preference" type="number" name="qty" defaultValue={1} min={0} max={20} required/><Button type="submit">Save my interest</Button></fieldset>{r.interest.length?<p className="fine">Your preferences: {r.interest.map((x:Row)=>`${r.options.find((v:Row)=>v.id===x.option_id)?.label||'Standard'} × ${x.qty}`).join(' · ')}</p>:null}</form>:null}
 {!admin&&r.kind==='trial'?r.canFeedback?<div className="trial-feedback"><h3>Should we keep it?</h3><p className="fine">One editable answer per recorded purchaser.</p><div className="inline-actions">{[[1,'Keep it'],[0,'Pass next time']].map(([v,label])=><Button key={v} variant={r.feedback?.keep===v?'default':'secondary'} aria-pressed={r.feedback?.keep===v} disabled={disabled} onClick={()=>action.send({action:'trialFeedback',id:r.id,version:r.version,keep:v})}>{label}</Button>)}</div></div>:<p className="fine">Feedback is available to recorded purchasers while the trial is open.</p>:null}
 {admin&&r.metrics?<>{r.kind==='interest'?<div className="stats compact-stats"><div className="stat"><small>Interested members</small><b>{r.metrics.interested.members}</b><span>Unique members across options</span></div><div className="stat"><small>Requested quantity</small><b>{r.metrics.interested.quantity}</b><span>Preferences, not paid orders</span></div></div>:<><div className="stats compact-stats"><div className="stat"><small>Net units sold</small><b>{r.metrics.sales.units}</b><span>{r.metrics.sales.buyers} unique buyers</span></div><div className="stat"><small>Recorded sales</small><b>{money(r.metrics.sales.revenue)}</b><span>Paid / tab, less corrections</span></div><div className="stat"><small>Margin after tax & losses</small><b>{r.metrics.sales.unknown_cost_units||r.metrics.losses.unknown_cost_units?'Unknown':money(r.metrics.sales.revenue-r.metrics.sales.tax-r.metrics.sales.known_cost-r.metrics.losses.known_cost)}</b><span>Known cost {money(r.metrics.sales.known_cost)}</span></div><div className="stat"><small>Keep-it votes</small><b>{r.metrics.feedback.keep} / {r.metrics.feedback.count}</b><span>{r.metrics.reviews.count} verified reviews · {r.metrics.reviews.average?Number(r.metrics.reviews.average).toFixed(1)+' stars':'No rating'}</span></div></div><p className="fine">{r.metrics.openingQuantity+r.metrics.receivedQuantity>0?'Sell-through: '+Math.round(r.metrics.sales.units/(r.metrics.openingQuantity+r.metrics.receivedQuantity)*100)+'% of recorded supply. ':''}{r.metrics.sales.units} net units sold from {r.metrics.openingQuantity} starting units plus {r.metrics.receivedQuantity} received during the trial. Trial-period sales use current corrections. Recorded waste / shrink: {r.metrics.losses.units} units ({money(r.metrics.losses.known_cost)} known cost). {r.metrics.sales.unknown_cost_units+r.metrics.losses.unknown_cost_units} units have unknown cost.</p></>}{r.metrics.demand.length?<div className="task-history"><h3>Option demand</h3>{r.metrics.demand.map((d:Row)=><div className="rank" key={d.option_id}><strong>{d.option_label}</strong><span>{d.quantity} items · {d.members} members</span></div>)}</div>:null}
 <div className="inline-actions">{r.product_id?<Button variant="secondary" onClick={()=>{setSelected('');onProduct?.(r.product_id)}}>Configure product</Button>:null}{r.state==='draft'?<Button disabled={disabled} onClick={()=>action.send({action:'initiativeOpen',id:r.id,version:r.version})}>Start {r.kind==='trial'?'trial':'interest check'}</Button>:null}</div>
 {['draft','open'].includes(r.state)?<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await action.send({action:f.get('outcome')==='preorder'?'initiativePreorder':'initiativeDecide',id:r.id,version:r.version,state:f.get('outcome'),note:f.get('note')})}}><fieldset disabled={disabled}><Field label="Outcome"><NativeSelect name="outcome">{r.kind==='trial'?<><option value="kept" disabled={r.state!=="open"}>Keep this product</option><option value="discontinued">End trial and hide product</option></>:<><option value="preorder" disabled={r.state!=='open'}>Open preorders using the same product</option><option value="closed">Close interest check</option></>}</NativeSelect></Field>{r.kind==='interest'?<p className="fine">Before opening preorders, configure option prices, preorder availability and publishing in Gear Manager. Interest preferences stay here; members place their own paid orders.</p>:null}<Field label="Decision visible to members"><textarea name="note" minLength={5} maxLength={1000} required/></Field><Button type="submit">Save decision</Button></fieldset></form>:null}
 {['draft','open'].includes(r.state)?<details className="loss-details"><summary>Change review date</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await action.send({action:'initiativeSchedule',id:r.id,version:r.version,endsAt:Date.parse(String(f.get('date'))+'T23:59:59Z'),note:f.get('note')})}}><fieldset disabled={disabled}><Field label="New review date · UTC" name="date" type="date" required/><Field label="Date change note (optional)" name="note" maxLength={1000}/><Button type="submit" variant="secondary">Update review date</Button></fieldset></form></details>:null}
 {r.kind==='trial'&&r.state==='open'?<details className="loss-details"><summary>Record waste or shrink</summary><p className="fine">This reduces available stock and records the loss. Do not also enter the same loss as a separate stock adjustment.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await action.send({action:'initiativeLoss',id:r.id,version:r.version,optionId:f.get('option')||'',qty:Number(f.get('qty')),kind:f.get('kind'),note:f.get('note')})}}><fieldset disabled={disabled}>{r.options.length?<Field label="Stock"><NativeSelect name="option"><option value="">Unallocated product stock</option>{r.options.map((v:Row)=><option key={v.id} value={v.id}>{v.label}</option>)}</NativeSelect></Field>:null}<div className="form-grid"><Field label="Quantity" name="qty" type="number" min={1} max={100000} required/><Field label="Reason type"><NativeSelect name="kind"><option value="waste">Waste / expiration</option><option value="shrink">Unexplained shrink</option></NativeSelect></Field></div><Field label="Required explanation" name="note" minLength={5} maxLength={1000} required/><Button variant="secondary" type="submit">Record stock loss</Button></fieldset></form></details>:null}
 </>:null}<OperationsFeedback action={action}/></>:null}</DialogContent></Dialog>
 </section>
}
