'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect} from '@/components/ui/native-select';
import {Field,money,date,type Row} from './shared';
const names:Row={awaiting_stock:'Awaiting stock',ready:'Ready for pickup',fulfilled:'Picked up',untracked:'Not tracked yet'};
export default function PickupBoard({data,send,busy,own=false}:{data:Row;send?:(b:Row)=>Promise<any>;busy?:boolean;own?:boolean}){
 const [filter,setFilter]=useState('open'),[message,setMessage]=useState(''),[items,setItems]=useState<Row[]>([]),[next,setNext]=useState<string|null>(null),[loading,setLoading]=useState(false);
 async function load(cursor?:string,signal?:AbortSignal){setLoading(true);setMessage('');try{const q=new URLSearchParams({dataset:'pickups',scope:own?'member':'admin',filter,...(cursor?{cursor}:{})});const r=await fetch('/api/history?'+q,{cache:'no-store',signal}),j=await r.json() as Record<string,any>;if(!r.ok)throw Error(j.error);const records=j.records.map((i:Row)=>({...i,order:{id:i.order_id,code:i.order_code,created_at:i.created_at,payer:i.payer,status:i.order_status}}));setItems(old=>cursor?[...old,...records]:records);setNext(j.nextCursor)}catch(e){if(!(e instanceof Error&&e.name==='AbortError'))setMessage(e instanceof Error?e.message:'Pickups could not load.')}finally{if(!signal?.aborted)setLoading(false)}}
 useEffect(()=>{const controller=new AbortController();setItems([]);void load(undefined,controller.signal);return()=>controller.abort()},[filter,own,data.updatedAt]);
 async function update(i:Row,status:string){setMessage('');if(await send?.({action:'fulfillment',itemId:i.id,previousStatus:i.fulfillment||null,status}))setMessage('Pickup status updated.')}
 return <section className="panel pickup-board"><div className="section-title"><div><h2>{own?'My gear orders':'Gear pickups'}</h2><p className="fine">Pickup progress and payment confirmation are tracked separately.</p></div><Field label="Show"><NativeSelect value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Open orders</option><option value="awaiting_stock">Awaiting stock</option><option value="ready">Ready for pickup</option><option value="fulfilled">Picked up</option><option value="all">All gear orders</option></NativeSelect></Field></div>{message?<p role="status">{message}</p>:null}{items.length?items.map((i:Row)=><article className="pickup-row" key={i.id}><div className="grow"><strong>{i.name} · {i.qty} {i.qty===1?'unit':'units'}</strong>{i.variant_label?<p>{i.variant_label}</p>:null}{i.personalization?<p className="personalization">Personalization: <strong>{i.personalization}</strong></p>:null}<small>{i.order.code} · {date(i.order.created_at)}{!own?' · '+i.order.payer:''}</small></div><div className="pickup-status"><span className="status">{names[i.fulfillment||'untracked']}</span><span className={'status '+(i.order.status==='paid'?'verified':'pending')}>{i.order.status==='paid'?'Payment confirmed':'Payment not confirmed'}</span><small>{money(i.price*i.qty)}</small></div>{!own?<div className="inline-actions"><Button type="button" variant="outline" disabled={busy||i.fulfillment==='awaiting_stock'} onClick={()=>update(i,'awaiting_stock')}>Awaiting stock</Button><Button type="button" variant="outline" disabled={busy||i.fulfillment==='ready'} onClick={()=>update(i,'ready')}>Ready</Button><Button type="button" disabled={busy||i.fulfillment==='fulfilled'||i.order.status!=='paid'} onClick={()=>update(i,'fulfilled')}>Picked up</Button></div>:null}</article>):<p className="fine">{loading?'Loading gear orders…':'No gear orders match this view.'}</p>}{next?<Button variant="outline" disabled={loading} onClick={()=>load(next)}>Load older gear orders</Button>:null}</section>
}
