'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect} from '@/components/ui/native-select';
import {Field,money,date,type Row} from './shared';
const names:Row={awaiting_stock:'Awaiting stock',ready:'Ready for pickup',fulfilled:'Picked up',untracked:'Not tracked yet'};
export default function PickupBoard({data,send,busy,own=false}:{data:Row;send?:(b:Row)=>Promise<any>;busy?:boolean;own?:boolean}){
 const [filter,setFilter]=useState('open'),[message,setMessage]=useState('');const source=own?data:data.admin,orders=new Map<string,Row>(source.orders.map((o:Row)=>[o.id,o])),items=source.items.filter((i:Row)=>i.fulfillment||data.products.some((p:Row)=>p.id===i.product_id&&p.category==='Gear')).map((i:Row)=>({...i,order:orders.get(i.order_id)})).filter((i:Row)=>i.order&&i.order.status!=='void'&&(filter==='all'||filter==='open'?filter==='all'||i.fulfillment!=='fulfilled':i.fulfillment===filter));
 async function update(i:Row,status:string){setMessage('');if(await send?.({action:'fulfillment',itemId:i.id,previousStatus:i.fulfillment||null,status}))setMessage('Pickup status updated.')}
 return <section className="panel pickup-board"><div className="section-title"><div><h2>{own?'My gear orders':'Gear pickups'}</h2><p className="fine">Pickup progress and payment confirmation are tracked separately.</p></div><Field label="Show"><NativeSelect value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Open orders</option><option value="awaiting_stock">Awaiting stock</option><option value="ready">Ready for pickup</option><option value="fulfilled">Picked up</option><option value="all">All gear orders</option></NativeSelect></Field></div>{message?<p role="status">{message}</p>:null}{items.length?items.map((i:Row)=><article className="pickup-row" key={i.id}><div className="grow"><strong>{i.name} · {i.qty} {i.qty===1?'unit':'units'}</strong>{i.variant_label?<p>{i.variant_label}</p>:null}{i.personalization?<p className="personalization">Personalization: <strong>{i.personalization}</strong></p>:null}<small>{i.order.code} · {date(i.order.created_at)}{!own?' · '+i.order.payer:''}</small></div><div className="pickup-status"><span className="status">{names[i.fulfillment||'untracked']}</span><span className={'status '+(i.order.status==='paid'?'verified':'pending')}>{i.order.status==='paid'?'Payment confirmed':'Payment not confirmed'}</span><small>{money(i.price*i.qty)}</small></div>{!own?<div className="inline-actions"><Button type="button" variant="outline" disabled={busy||i.fulfillment==='awaiting_stock'} onClick={()=>update(i,'awaiting_stock')}>Awaiting stock</Button><Button type="button" variant="outline" disabled={busy||i.fulfillment==='ready'} onClick={()=>update(i,'ready')}>Ready</Button><Button type="button" disabled={busy||i.fulfillment==='fulfilled'||i.order.status!=='paid'} onClick={()=>update(i,'fulfilled')}>Picked up</Button></div>:null}</article>):<p className="fine">No gear orders match this view.</p>}</section>
}
