'use client';
import {useEffect,useState,useRef} from 'react';
import {CheckCircle2,ArrowUpRight,Inbox} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Field,money,date,type Row} from './shared';
import {useOperations,OperationsFeedback,operationsRead} from './operations-action';
import './admin-experience.css';
const labels:Record<string,string>={payment:'Payments',tab:'Tabs',email:'Email changes',reset:'Password resets',stock:'Stock',report:'Moderation',request:'Item requests',team:'Team questions',pickup:'Gear fulfillment',trial:'Trial reviews',adjustment:'Adjustments',guest:'Guest fulfillment',profile:'Profile approvals','profile-report':'Profile reports'};
export default function TaskInbox({member,onAction,initialType=''}:{member:Row;onAction:(tab:string,target:string,person:string,type:string,reference:string)=>void;initialType?:string}){
 const [data,setData]=useState<Row>({records:[],admins:[],counts:[],brief:{},events:[]}),[filter,setFilter]=useState('open'),[type,setType]=useState(initialType),[search,setSearch]=useState(''),[selected,setSelected]=useState(''),[error,setError]=useState('');
 const [picked,setPicked]=useState<Row[]>([]),[bulk,setBulk]=useState(''),[bulkResult,setBulkResult]=useState<Row|null>(null),[batchAssignee,setBatchAssignee]=useState(member.id),[snoozeDays,setSnoozeDays]=useState('1'),[batchNote,setBatchNote]=useState('');
 const sequence=useRef(0);
 async function load(offset=0){const ticket=++sequence.current;const j=await operationsRead({kind:'inbox',filter,type,search,taskKey:selected,offset:String(offset)});if(ticket!==sequence.current)return;setData(old=>offset?{...j,records:[...old.records,...j.records]}:j);setError('')}
 const action=useOperations(()=>load()),disabled=action.busy||!!action.pending,t=data.task;
 useEffect(()=>{let valid=true;const timer=setTimeout(()=>{if(valid)void load().catch(e=>setError(e.message))},150);return()=>{valid=false;sequence.current++;clearTimeout(timer)}},[filter,type,search,selected]);
 useEffect(()=>{setPicked([]);setBulkResult(null)},[filter,type,search]);
 const count=(name:string)=>data.counts.find((x:Row)=>x.type===name)?.count||0;
 const reviewable=picked.filter(r=>r.dismissible&&r.active&&r.status!=='resolved');
 function toggle(r:Row){setPicked(old=>old.some(x=>x.task_key===r.task_key)?old.filter(x=>x.task_key!==r.task_key):old.length<50?[...old,r]:old)}
 async function submitBulk(){const r=await action.send({action:'taskBulk',operation:bulk,items:picked.map(x=>({taskKey:x.task_key,version:x.version,revision:x.revision})),assignee:batchAssignee,snoozeUntil:Date.now()+Number(snoozeDays)*86400000,note:batchNote});if(r){setBulkResult(r);setPicked([]);setBulk('');setBatchNote('')}}
 return <>
 <section className="panel morning-brief"><div><span className="eyebrow">Today</span><h2>Needs attention</h2><p className="fine">Start here. Each task opens the control that owns the record.</p></div><div className="brief-metrics"><div><span>Yesterday’s sales · UTC</span><strong>{money(data.brief.yesterday_sales||0)}</strong></div><div><span>Outstanding tabs</span><strong>{money(data.brief.outstanding_tabs||0)}</strong></div><button type="button" onClick={()=>{setFilter('open');setType('payment')}}><span>Payment confirmations</span><strong>{count('payment')}</strong></button><button type="button" onClick={()=>{setFilter('open');setType('stock')}}><span>Low-stock items / options</span><strong>{count('stock')}</strong></button></div><p className="fine">Counts include snoozed tasks. Snoozing never settles a balance or changes an order.</p></section>
 <section className="panel"><div className="board-toolbar"><Field label="Tasks"><NativeSelect value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Open tasks</option><option value="mine">Assigned to me</option><option value="snoozed">Snoozed</option><option value="resolved">Resolved</option><option value="all">All records</option></NativeSelect></Field><Field label="Type"><NativeSelect value={type} onChange={e=>setType(e.target.value)}><option value="">Every type</option>{type.includes(',')?<option value={type}>Selected work types</option>:null}{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</NativeSelect></Field><Field label="Find a task"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or reference" maxLength={100}/></Field><Button variant="ghost" onClick={()=>load().catch(e=>setError(e.message))}>Refresh</Button></div>
 <OperationsFeedback action={action}/>{error?<p className="notice error" role="alert">{error}</p>:null}
 {bulkResult?<div className="notice success" role="status"><strong>{bulkResult.applied} task{bulkResult.applied===1?'':'s'} updated.</strong>{bulkResult.skipped?<p>{bulkResult.skipped} skipped because the record changed or that action did not apply. Financial and access records stay protected.</p>:null}</div>:null}
 {data.records.length?<div className="task-bulk-toolbar"><Button variant="secondary" disabled={disabled} onClick={()=>setPicked(data.records.filter((r:Row)=>r.status!=='resolved').slice(0,50))}>Select visible tasks</Button>{picked.length?<><span className="fine">{picked.length} selected · maximum 50</span><Button variant="ghost" disabled={disabled} onClick={()=>setPicked([])}>Clear selection</Button><Button variant="secondary" disabled={disabled} onClick={()=>setBulk('assign')}>Assign</Button><Button variant="secondary" disabled={disabled} onClick={()=>setBulk(filter==='snoozed'?'unsnooze':'snooze')}>{filter==='snoozed'?'Restore reminders':'Snooze'}</Button><Button disabled={disabled||!reviewable.length} onClick={()=>setBulk('review')}>Mark adjustments reviewed ({reviewable.length})</Button></>:null}</div>:null}
 <div className="operations-list">{data.records.map((r:Row)=><div className="task-select-row" key={r.task_key}><input type="checkbox" aria-label={'Select '+r.title+' '+r.reference} checked={picked.some(x=>x.task_key===r.task_key)} disabled={disabled||r.status==='resolved'||(picked.length>=50&&!picked.some(x=>x.task_key===r.task_key))} onChange={()=>toggle(r)}/><button type="button" className="operation-row" onClick={()=>setSelected(r.task_key)}><span><strong>{r.title}</strong><small>{r.person} · {r.reference}</small>{r.snoozed_until?<small>Snoozed until {date(r.snoozed_until)}</small>:r.deadline&&r.active?<small>{r.deadline<Date.now()?'Due since ':'Due '}{date(r.deadline)}</small>:null}</span><span className="operation-summary"><span className={'status '+(r.status==='resolved'?'resolved':r.severity==='high'?'pending':'open')}>{r.status==='resolved'?'Resolved':r.severity==='high'?'Needs attention':r.status==='in_progress'?'In progress':'Open'}</span>{['payment','tab'].includes(r.type)?<strong>{money(r.amount)}</strong>:r.type==='stock'?<small>{r.amount} on hand</small>:null}<small>{data.admins.find((a:Row)=>a.id===r.assignee)?.name||'Unassigned'}</small></span></button></div>)}</div>
 {!data.records.length?<div className="empty"><Inbox size={28}/><h3>No tasks in this view.</h3><p>Related records update this inbox as work is completed.</p></div>:null}{data.nextOffset!=null?<Button variant="secondary" onClick={()=>load(data.nextOffset).catch(e=>setError(e.message))}>Load more tasks</Button>:null}</section>
 <Dialog open={!!bulk} onOpenChange={o=>{if(!o&&!disabled)setBulk('')}}><DialogContent className="pilot-dialog task-dialog"><DialogTitle>{bulk==='review'?'Review adjustment notifications':bulk==='assign'?'Assign selected tasks':bulk==='unsnooze'?'Restore reminders':'Snooze reminders'}</DialogTitle><DialogDescription>{picked.length} selected tasks. This action only changes the team’s workflow metadata.</DialogDescription><form className="road-stack" onSubmit={e=>{e.preventDefault();void submitBulk()}}><fieldset disabled={disabled} className="road-stack">{bulk==='review'?<p>Mark {reviewable.length} adjustment notification{reviewable.length===1?'':'s'} reviewed. {picked.length-reviewable.length} other task{picked.length-reviewable.length===1?'':'s'} will be skipped. Purchases, payments, balances, inventory, and access remain unchanged.</p>:null}{bulk==='assign'?<Field label="Assign to"><NativeSelect value={batchAssignee} onChange={e=>setBatchAssignee(e.target.value)}><option value="">Unassigned</option>{data.admins.map((a:Row)=><option value={a.id} key={a.id}>{a.name}</option>)}</NativeSelect></Field>:null}{bulk==='snooze'?<><Field label="Bring reminders back in"><NativeSelect value={snoozeDays} onChange={e=>setSnoozeDays(e.target.value)}><option value="1">1 day</option><option value="3">3 days</option><option value="7">7 days</option></NativeSelect></Field><p className="fine">Outstanding work stays in dashboard totals. Tasks also return if their source details change.</p></>:null}<Field label="Internal note (optional)"><textarea maxLength={1000} value={batchNote} onChange={e=>setBatchNote(e.target.value)}/></Field><Button type="submit">{bulk==='review'?'Confirm review':bulk==='assign'?'Save assignment':bulk==='unsnooze'?'Restore reminders':'Snooze reminders'}</Button></fieldset></form><OperationsFeedback action={action}/></DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={o=>{if(!o&&!disabled)setSelected('')}}><DialogContent className="pilot-dialog task-dialog"><DialogTitle>{t?.title||'Task details'}</DialogTitle><DialogDescription>{t?`${t.person} · ${t.reference}`:'Loading…'}</DialogDescription>{t?<><div className="inline-actions"><Button onClick={()=>{setSelected('');onAction(t.destination,t.target,t.person,t.type,t.reference)}}>Open {labels[t.type]?.toLowerCase()||'record'} <ArrowUpRight size={16}/></Button>{t.status==='resolved'?<span className="status resolved"><CheckCircle2 size={14}/>Resolved</span>:null}</div><p className="fine">Task notes and assignment are private to verified administrators. Resolving a financial task requires completing its linked action.</p>
 <form key={t.task_key+':'+t.version} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await action.send({action:'taskUpdate',taskKey:t.task_key,version:t.version,assignee:f.get('assignee'),state:f.get('state'),dueAt:f.get('due')?Date.parse(String(f.get('due'))+'T12:00:00Z'):null,note:f.get('note')})}}><fieldset disabled={disabled}><div className="form-grid"><Field label="Assigned to"><NativeSelect name="assignee" defaultValue={t.assignee||''}><option value="">Unassigned</option>{data.admins.map((a:Row)=><option key={a.id} value={a.id}>{a.name}</option>)}</NativeSelect></Field><Field label="Work status"><NativeSelect name="state" defaultValue={t.status}><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved" disabled={t.active&&!t.dismissible}>Resolved</option></NativeSelect></Field></div><Field label="Follow-up date · UTC" name="due" type="date" defaultValue={t.deadline?new Date(t.deadline).toISOString().slice(0,10):''}/><Field label="Internal note (optional)"><textarea name="note" maxLength={1000}/></Field><Button type="submit">Save task</Button></fieldset></form>
 {t.type==='tab'&&t.active?<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await action.send({action:'tabReminder',taskKey:t.task_key,note:f.get('note')})}}><fieldset disabled={disabled}><h3>Record a reminder</h3><p className="fine">Record a conversation or reminder you actually sent. This does not email or charge the member.</p><Field label="Reminder details" name="note" minLength={5} maxLength={1000} required/><Button type="submit" variant="secondary">Record reminder</Button></fieldset></form>:null}
 <OperationsFeedback action={action}/><div className="task-history"><h3>Task history</h3>{data.events.map((event:Row)=><article key={event.id}><strong>{event.actor_name} · {event.kind==='reminder'?'Reminder':event.kind.startsWith('bulk_')?'Bulk '+event.kind.slice(5):'Task update'}</strong><p>{event.note}</p><small>{date(event.created_at)}</small></article>)}{!data.events.length?<p className="fine">No internal notes yet.</p>:null}</div></>:null}</DialogContent></Dialog>
 </>
}
