'use client';
import {useEffect,useState,useRef} from 'react';
import {CheckCircle2,ArrowUpRight,Inbox} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Field,money,date,type Row} from './shared';
import {useOperations,OperationsFeedback,operationsRead} from './operations-action';
const labels:Record<string,string>={payment:'Payments',tab:'Tabs',email:'Email changes',reset:'Password resets',stock:'Stock',report:'Moderation',request:'Item requests',team:'Team questions',pickup:'Gear fulfillment',trial:'Trial reviews',adjustment:'Adjustments'};
export default function TaskInbox({member,onAction}:{member:Row;onAction:(tab:string,target:string,person:string)=>void}){
 const [data,setData]=useState<Row>({records:[],admins:[],counts:[],brief:{},events:[]}),[filter,setFilter]=useState('open'),[type,setType]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState(''),[error,setError]=useState('');
 const sequence=useRef(0);
 async function load(offset=0){const ticket=++sequence.current;const j=await operationsRead({kind:'inbox',filter,type,search,taskKey:selected,offset:String(offset)});if(ticket!==sequence.current)return;setData(old=>offset?{...j,records:[...old.records,...j.records]}:j);setError('')}
 const action=useOperations(()=>load()),disabled=action.busy||!!action.pending,t=data.task;
 useEffect(()=>{let valid=true;const timer=setTimeout(()=>{if(valid)void load().catch(e=>setError(e.message))},150);return()=>{valid=false;sequence.current++;clearTimeout(timer)}},[filter,type,search,selected]);
 const count=(name:string)=>data.counts.find((x:Row)=>x.type===name)?.count||0;
 return <>
 <section className="panel morning-brief"><div><span className="eyebrow">Today</span><h2>Needs attention</h2><p className="fine">Start here. Each task opens the control that owns the record.</p></div><div className="brief-metrics"><div><span>Yesterday’s sales · UTC</span><strong>{money(data.brief.yesterday_sales||0)}</strong></div><div><span>Outstanding tabs</span><strong>{money(data.brief.outstanding_tabs||0)}</strong></div><button type="button" onClick={()=>{setFilter('open');setType('payment')}}><span>Payment confirmations</span><strong>{count('payment')}</strong></button><button type="button" onClick={()=>{setFilter('open');setType('stock')}}><span>Low-stock items / options</span><strong>{count('stock')}</strong></button></div></section>
 <section className="panel"><div className="board-toolbar"><Field label="Tasks"><NativeSelect value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Open tasks</option><option value="mine">Assigned to me</option><option value="resolved">Resolved</option><option value="all">All records</option></NativeSelect></Field><Field label="Type"><NativeSelect value={type} onChange={e=>setType(e.target.value)}><option value="">Every type</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</NativeSelect></Field><Field label="Find a task"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or reference" maxLength={100}/></Field><Button variant="ghost" onClick={()=>load().catch(e=>setError(e.message))}>Refresh</Button></div>
 <OperationsFeedback action={action}/>{error?<p className="notice error" role="alert">{error}</p>:null}<div className="operations-list">{data.records.map((r:Row)=><button type="button" className="operation-row" key={r.task_key} onClick={()=>setSelected(r.task_key)}><span><strong>{r.title}</strong><small>{r.person} · {r.reference}</small>{r.deadline&&r.active?<small>{r.deadline<Date.now()?'Due since ':'Due '}{date(r.deadline)}</small>:null}</span><span className="operation-summary"><span className={'status '+(r.status==='resolved'?'resolved':r.severity==='high'?'pending':'open')}>{r.status==='resolved'?'Resolved':r.severity==='high'?'Needs attention':r.status==='in_progress'?'In progress':'Open'}</span>{['payment','tab'].includes(r.type)?<strong>{money(r.amount)}</strong>:r.type==='stock'?<small>{r.amount} on hand</small>:null}<small>{data.admins.find((a:Row)=>a.id===r.assignee)?.name||'Unassigned'}</small></span></button>)}</div>
 {!data.records.length?<div className="empty"><Inbox size={28}/><h3>No tasks in this view.</h3><p>Related records update this inbox as work is completed.</p></div>:null}{data.nextOffset!=null?<Button variant="secondary" onClick={()=>load(data.nextOffset).catch(e=>setError(e.message))}>Load more tasks</Button>:null}</section>
 <Dialog open={!!selected} onOpenChange={o=>{if(!o&&!disabled)setSelected('')}}><DialogContent className="pilot-dialog task-dialog"><DialogTitle>{t?.title||'Task details'}</DialogTitle><DialogDescription>{t?`${t.person} · ${t.reference}`:'Loading…'}</DialogDescription>{t?<><div className="inline-actions"><Button onClick={()=>{setSelected('');onAction(t.destination,t.target,t.person)}}>Open {labels[t.type]?.toLowerCase()||'record'} <ArrowUpRight size={16}/></Button>{t.status==='resolved'?<span className="status resolved"><CheckCircle2 size={14}/>Resolved</span>:null}</div><p className="fine">Task notes and assignment are private to verified administrators. Resolving a financial task requires completing its linked action.</p>
 <form key={t.task_key+':'+t.version} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await action.send({action:'taskUpdate',taskKey:t.task_key,version:t.version,assignee:f.get('assignee'),state:f.get('state'),dueAt:f.get('due')?Date.parse(String(f.get('due'))+'T12:00:00Z'):null,note:f.get('note')})}}><fieldset disabled={disabled}><div className="form-grid"><Field label="Assigned to"><NativeSelect name="assignee" defaultValue={t.assignee||''}><option value="">Unassigned</option>{data.admins.map((a:Row)=><option key={a.id} value={a.id}>{a.name}</option>)}</NativeSelect></Field><Field label="Work status"><NativeSelect name="state" defaultValue={t.status}><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved" disabled={t.active&&!t.dismissible}>Resolved</option></NativeSelect></Field></div><Field label="Follow-up date · UTC" name="due" type="date" defaultValue={t.deadline?new Date(t.deadline).toISOString().slice(0,10):''}/><Field label="Internal note"><textarea name="note" required minLength={5} maxLength={1000}/></Field><Button type="submit">Save task note</Button></fieldset></form>
 {t.type==='tab'&&t.active?<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await action.send({action:'tabReminder',taskKey:t.task_key,note:f.get('note')})}}><fieldset disabled={disabled}><h3>Record a reminder</h3><p className="fine">Record a conversation or reminder you actually sent. This does not email or charge the member.</p><Field label="Reminder details" name="note" minLength={5} maxLength={1000} required/><Button type="submit" variant="secondary">Record reminder</Button></fieldset></form>:null}
 <OperationsFeedback action={action}/><div className="task-history"><h3>Task history</h3>{data.events.map((event:Row)=><article key={event.id}><strong>{event.actor_name} · {event.kind==='reminder'?'Reminder':'Task update'}</strong><p>{event.note}</p><small>{date(event.created_at)}</small></article>)}{!data.events.length?<p className="fine">No internal notes yet.</p>:null}</div></>:null}</DialogContent></Dialog>
 </>
}
