/* eslint-disable */
// Generated by Wrangler by running `wrangler types identity-worker-env.d.ts --include-runtime=false --strict-vars=false` (hash: 7b1590613960accb1c59aae698a89c1e)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
	IDENTITY_ENABLED: string;
	IDENTITY_ROLLOUT: string;
	IDENTITY_BETA_MEMBER_IDS: string;
	IDENTITY_GOOGLE_ENABLED: string;
	IDENTITY_GOOGLE_FRESH_ENABLED: string;
	IDENTITY_MICROSOFT_ENABLED: string;
	IDENTITY_PASSKEY_ENABLED: string;
	IDENTITY_GOOGLE_BOOTSTRAP_ENABLED: string;
	IDENTITY_BASE_DOMAIN: string;
	IDENTITY_OWNER_MEMBER_ID: string;
	IDENTITY_ADMIN_ACCESS_AUD: string;
	IDENTITY_REQUEST_RETENTION_DAYS: string;
	IDENTITY_SESSION_RETENTION_DAYS: string;
	IDENTITY_AUDIT_RETENTION_DAYS: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "IDENTITY_ENABLED" | "IDENTITY_ROLLOUT" | "IDENTITY_BETA_MEMBER_IDS" | "IDENTITY_GOOGLE_ENABLED" | "IDENTITY_GOOGLE_FRESH_ENABLED" | "IDENTITY_MICROSOFT_ENABLED" | "IDENTITY_PASSKEY_ENABLED" | "IDENTITY_GOOGLE_BOOTSTRAP_ENABLED" | "IDENTITY_BASE_DOMAIN" | "IDENTITY_OWNER_MEMBER_ID" | "IDENTITY_ADMIN_ACCESS_AUD" | "IDENTITY_REQUEST_RETENTION_DAYS" | "IDENTITY_SESSION_RETENTION_DAYS" | "IDENTITY_AUDIT_RETENTION_DAYS">> {}
}
