import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fixture} from './identity-fixture.mjs';
const f=await fixture(),{db,sqlite}=f;
const {passwordHash}=await f.module('lib/auth/password');
const C=await f.module('lib/identity/common'),F=await f.module('lib/identity/flows'),M=await f.module('lib/identity/manage'),S=await f.module('lib/identity/sessions'),I=await f.module('lib/identity/imports'),P=await f.module('lib/identity/providers');
const env={IDENTITY_ENABLED:'true',IDENTITY_BASE_DOMAIN:'identity.test',IDENTITY_GOOGLE_ENABLED:'true',IDENTITY_MICROSOFT_ENABLED:'true',IDENTITY_PASSKEY_ENABLED:'true',IDENTITY_GOOGLE_BOOTSTRAP_ENABLED:'true',GOOGLE_CLIENT_ID:'google-fixture',GOOGLE_CLIENT_SECRET:'synthetic-only',MICROSOFT_CLIENT_ID:'microsoft-fixture',MICROSOFT_CLIENT_SECRET:'synthetic-only',IDENTITY_OWNER_MEMBER_ID:'owner'};
const now=Date.now(),password='Synthetic existing method 123456';
env.IDENTITY_ROLLOUT='all-approved';
sqlite.exec("INSERT INTO members(id,email,name,role,debt,credit) VALUES('owner','owner@example.test','Owner','admin',0,0),('alice','Alice@gmail.com','Alice','member',725,250),('bob','bob@example.test','Bob','member',300,175),('no-password','no-password@example.test','Passkey only','member',0,0)");
const existingHash=await passwordHash(password);sqlite.prepare('INSERT INTO auth_credentials VALUES(?,?,?)').run('owner',existingHash,now);sqlite.prepare('INSERT INTO auth_credentials VALUES(?,?,?)').run('alice',existingHash,now);
sqlite.exec(readFileSync('IDENTITY-SCHEMA.sql','utf8'));const handle=sqlite.prepare("SELECT user_handle FROM identity_state WHERE member_id='alice'").get().user_handle;
sqlite.exec(readFileSync('IDENTITY-SCHEMA.sql','utf8'));assert.equal(sqlite.prepare("SELECT user_handle FROM identity_state WHERE member_id='alice'").get().user_handle,handle,'repeat migration preserves WebAuthn handles');
let checks=1;const check=(v,label)=>{assert.ok(v,label);checks++;};const rejects=async(fn,label)=>{await assert.rejects(fn,label);checks++;};
for(const bad of ['//evil.test','https://evil.test','/\\evil.test','/%252f%252fevil.test','/products/a?mutation=buy','/products/%2e%2e','/\n'])check(C.safeReturn(bad)==='/','reject unsafe return '+JSON.stringify(bad));
check(C.safeReturn('/products/item-1')==='/products/item-1','safe product return');
check(C.matchEmail(' Alice+Tag@GMAIL.COM ')==='Alice+Tag@gmail.com','local part preserved');
for(const bad of ['"a"@example.test','ü@example.test','a..b@example.test','a@evil.test/path','a@example..test'])check(C.matchEmail(bad)===null,'unsafe email misses into review');
const google=(subject,email='Alice@gmail.com')=>({kind:'google',issuer:P.ISSUERS.google,subject,clientId:env.GOOGLE_CLIENT_ID,email,bootstrapEmail:email,tenant:null,objectId:null,authTime:Date.now()});
check(P.providerProof('google','client',{iss:P.ISSUERS.google,sub:'a',email:'third@external.test',email_verified:true}).bootstrapEmail===null,'third-party verified Google email is not bootstrap authority');
check(P.providerProof('google','client',{iss:P.ISSUERS.google,sub:'a',email:'Alice@gmail.com',email_verified:'true'}).bootstrapEmail===null,'email_verified must be boolean');
check(P.providerProof('google','client',{iss:P.ISSUERS.google,sub:'a',email:'alice@workspace.test',email_verified:true,hd:'workspace.test'}).bootstrapEmail==='alice@workspace.test','hosted Workspace exact match');
assert.throws(()=>P.providerProof('microsoft','client',{iss:P.ISSUERS.microsoft,sub:'a',tid:'organizational'}));checks++;
check(P.providerProof('microsoft','client',{iss:P.ISSUERS.microsoft,sub:'a',tid:P.CONSUMER_TENANT,email:'Alice@gmail.com',xms_edov:true}).bootstrapEmail===null,'Microsoft bootstrap remains release-gated');
const ownerPrincipal={id:'principal-owner',member_id:'owner',identity_owner:1,issuer:'https://fixture.cloudflareaccess.com',subject:'owner-subject',expiresAt:Date.now()+1800000};
sqlite.prepare('INSERT INTO identity_admin_principals(id,issuer,subject,member_id,identity_owner,provisioned_at,evidence) VALUES(?,?,?,?,1,?,?)').run(ownerPrincipal.id,ownerPrincipal.issuer,ownerPrincipal.subject,'owner',now,'synthetic fixture');
const ownerToken=await S.adminSession(db,ownerPrincipal),ownerRequest=new Request('https://admin.identity.test',{headers:{Cookie:C.ADMIN_COOKIE+'='+ownerToken}}),owner=await S.readSession(db,ownerRequest,'admin');check(owner?.memberId==='owner','explicit principal creates separate admin session');
check(await S.readSession(db,new Request('https://identity.test',{headers:{Cookie:'__Host-supply-session='+ownerToken}}),'member')===null,'admin cookie token cannot become a member session');
const ownerApproval=async(payload)=>{
 const dest=C.digest(C.random()),fid=await F.newFlow(db,dest,'/identity',owner,'owner:'+M.payloadHash(payload),payload);
 await F.freshPassword(db,await C.flow(db,fid),password);const url=new URL(await F.issueHandoff(db,env,fid)),parts=new URLSearchParams(url.hash.slice(1));
 const result=await F.redeem(db,env,fid,parts.get('code'),dest,'admin',owner);return new URL(result.next,'https://admin.identity.test').searchParams.get('approval');
};
const ownerAction=async payload=>M.adminMutation(db,env,owner,payload,await ownerApproval(payload));
const invitePayload={operation:'invite',target:'alice',purpose:'enroll',identityVerified:true};
const approvalId=await ownerApproval(invitePayload);
await rejects(()=>M.adminMutation(db,env,owner,{...invitePayload,target:'bob'},approvalId),'fresh proof is action and target bound');
let invite=await M.adminMutation(db,env,owner,invitePayload,approvalId);check(!JSON.stringify(sqlite.prepare("SELECT * FROM identity_grants WHERE kind='invite'").all()).includes(new URL(invite.url).hash.slice(8)),'raw invitation absent from database');
await rejects(()=>M.adminMutation(db,env,owner,invitePayload,approvalId),'approval cannot be reused');
const oldInvite=new URL(invite.url).hash.slice(8);invite=await ownerAction(invitePayload);
await rejects(()=>F.claimInvite(db,oldInvite,C.digest('register-browser')),'superseded invitation rejected');
const inviteToken=new URL(invite.url).hash.slice(8),reg=C.digest('register-browser'),dest=C.digest('destination-browser');
const fid=await F.claimInvite(db,inviteToken,reg);check(sqlite.prepare("SELECT status FROM identity_grants WHERE token_hash=?").get(C.digest(inviteToken)).status==='pending','claim does not consume invite');
await rejects(()=>F.bridgeInvite(db,fid,dest,{memberId:'bob'}),'wrong current member is not silently replaced');
await F.bridgeInvite(db,fid,dest,null);
await F.storeEnrollmentProof(db,await C.flow(db,fid),google('alice-subject','different@example.test'));
const credential=await F.finishEnrollment(db,await C.flow(db,fid),'Google');check(credential.member_id==='alice','invite targets immutable member even when provider email differs');
await rejects(async()=>F.finishEnrollment(db,await C.flow(db,fid),'duplicate'),'one invitation attaches one credential');
const handoff=new URL(await F.issueHandoff(db,env,fid)),code=new URLSearchParams(handoff.hash.slice(1)).get('code');
await rejects(()=>F.redeem(db,env,fid,code,C.digest('other-browser'),'member',null),'handoff needs original destination browser');
await rejects(()=>F.redeem(db,env,fid,code,dest,'admin',null),'handoff is audience bound');
const signed=await F.redeem(db,env,fid,code,dest,'member',null);check(!!signed.token,'one-time handoff creates member session');
await rejects(()=>F.redeem(db,env,fid,code,dest,'member',null),'handoff replay fails');
let alice=await S.readSession(db,new Request('https://identity.test',{headers:{Cookie:'__Host-supply-session='+signed.token}}),'member');check(alice.memberId==='alice','provider session does not require password join');
const session=sqlite.prepare('SELECT * FROM identity_sessions WHERE token_hash=?').get(C.digest(signed.token));check(session.absolute_expires_at-session.created_at===2592000000,'member absolute duration retained');check(sqlite.prepare('SELECT expires_at-created_at n FROM auth_sessions WHERE token_hash=?').get(C.digest(signed.token)).n===604800000,'member idle duration retained');
const flow2=await F.newFlow(db,C.digest('d2'),'/products/snack');const linked=await F.associateProvider(db,env,google('alice-subject','changed@other.test'),await C.flow(db,flow2));check(linked.member_id==='alice','linked subject survives observed email change');
await F.authenticated(db,await C.flow(db,flow2),linked);const code2=new URLSearchParams(new URL(await F.issueHandoff(db,env,flow2)).hash.slice(1)).get('code');
await M.ownMutation(db,env,alice,{operation:'logoutAll'});
await rejects(()=>F.redeem(db,env,flow2,code2,C.digest('d2'),'member',null),'sign out everywhere invalidates pending handoffs');
check(await S.readSession(db,new Request('https://identity.test',{headers:{Cookie:'__Host-supply-session='+signed.token}}),'member')===null,'sign out everywhere revokes session');
const oldFlow=await F.newFlow(db,C.digest('old'),'/');sqlite.prepare("UPDATE identity_state SET epoch=epoch+1 WHERE member_id='alice'").run();
await rejects(async()=>F.authenticated(db,await C.flow(db,oldFlow),linked),'pending pre-epoch auth cannot restore access');
sqlite.prepare("UPDATE identity_credentials SET status='revoked' WHERE id=?").run(credential.id);
await rejects(async()=>F.associateProvider(db,env,google('alice-subject'),await C.flow(db,oldFlow)),'revoked subject never bootstraps');
check(sqlite.prepare('SELECT member_id FROM identity_credentials WHERE id=?').get(credential.id).member_id==='alice','revoked identity remains reserved');
// Bootstrap is explicitly granted, provider-scoped and unique under two claimants.
await ownerAction({operation:'bootstrap',target:'bob',provider:'google',email:'Bob@gmail.com'});
const loginA=await F.newFlow(db,C.digest('login-a'),'/'),loginB=await F.newFlow(db,C.digest('login-b'),'/');
const [fa,fb]=await Promise.all([C.flow(db,loginA),C.flow(db,loginB)]);
const race=await Promise.allSettled([F.associateProvider(db,env,google('bob-provider-a','Bob@gmail.com'),fa),F.associateProvider(db,env,google('bob-provider-b','Bob@gmail.com'),fb)]);
check(race.filter(r=>r.status==='fulfilled'&&r.value).length===1,'bootstrap has one concurrent winner');
const before=sqlite.prepare('SELECT count(*) n FROM members').get().n;
const unmatchedFlow=await F.newFlow(db,C.digest('unmatched'),'/');check(await F.associateProvider(db,env,google('unknown-subject','unlisted@gmail.com'),await C.flow(db,unmatchedFlow))===null,'valid unmatched provider enters review without session');
check(sqlite.prepare('SELECT count(*) n FROM members').get().n===before,'provider never creates membership');
const request=sqlite.prepare("SELECT id FROM identity_requests WHERE subject='unknown-subject'").get();
await ownerAction({operation:'reviewLink',target:'bob',requestId:request.id,reason:'Synthetic known-person check',identityVerified:true});
check(sqlite.prepare("SELECT count(*) n FROM auth_sessions WHERE member_id='bob'").get().n===0,'review approval does not log stale browser in');
// Import preview is read-only for authority, and committed rows never renew grants.
sqlite.prepare("DELETE FROM auth_limits WHERE id=?").run(C.digest('identity-password:owner'));
const csv='member_id,display_name,contact_email,google_bootstrap_email,access_enabled\nbob,"Bob, Jr",contact@example.test,Bob@gmail.com,true\nmissing,Unknown,,,true';
const preview=await I.previewImport(db,env,owner,csv);check(preview.rows[0].grants[0].create===false,'consumed bootstrap is reserved during preview');check(preview.rows[1].status==='Conflict','unknown ID is not automatically matched or created');
const payload={operation:'importCommit',batch:preview.batch,hash:preview.hash,rows:[1,2]},grant=await ownerApproval(payload);
const committed=await I.commitImport(db,env,owner,payload,grant);check(committed.applied===1&&committed.conflicts===1,'import reports exact per-row success and conflict');
check(sqlite.prepare("SELECT status FROM identity_grants WHERE provider='google' AND match_email='Bob@gmail.com'").get().status==='consumed','import cannot reauthorize consumed grant');
const again=await I.commitImport(db,env,owner,payload,await ownerApproval(payload));check(again.alreadyApplied===1,'import retry is idempotent');
const stale=await I.previewImport(db,env,owner,'member_id,display_name\nbob,Stale name');sqlite.prepare("UPDATE members SET name='Newer name' WHERE id='bob'").run();const stalePayload={operation:'importCommit',batch:stale.batch,hash:stale.hash,rows:[1]};
check((await I.commitImport(db,env,owner,stalePayload,await ownerApproval(stalePayload))).conflicts===1,'stale preview cannot overwrite newer details');
for(const bad of ['member_id,role\nbob,admin','member_id,balance\nbob,0','email,display_name\nbob@example.test,Bob']){assert.throws(()=>I.parseRoster(bad));checks++;}
const preserved=sqlite.prepare("SELECT id,debt,credit FROM members WHERE id IN ('alice','bob') ORDER BY id").all().map(v=>({...v}));assert.deepEqual(preserved,[{id:'alice',debt:725,credit:250},{id:'bob',debt:300,credit:175}]);checks++;
console.log(`${checks} identity state, browser binding, containment, owner authority, and import checks passed (synthetic fixtures).`);
sqlite.close();
