// Actual compiled Worker + isolated D1. All providers/MFA here are synthetic.
import assert from 'node:assert/strict';
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {scryptSync,createHash,randomBytes} from 'node:crypto';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
const require=createRequire(import.meta.url),{Miniflare}=require(require.resolve('miniflare',{paths:[require.resolve('wrangler/package.json')]}));
const {privateKey,publicKey}=await generateKeyPair('RS256'),jwk={...await exportJWK(publicKey),kid:'synthetic-access',alg:'RS256',use:'sig'};
const issuer='https://fixture.cloudflareaccess.com',audience='fixture-admin-audience',domain='test.local';
const token=async(subject='owner-subject',iat=Math.floor(Date.now()/1000),aud=audience)=>new SignJWT({email:'irrelevant@example.test'}).setProtectedHeader({alg:'RS256',kid:jwk.kid}).setIssuer(issuer).setAudience(aud).setSubject(subject).setIssuedAt(iat).setExpirationTime(iat+1800).sign(privateKey);
const settings={IDENTITY_ENABLED:'true',IDENTITY_ROLLOUT:'all-approved',IDENTITY_BASE_DOMAIN:domain,IDENTITY_OWNER_MEMBER_ID:'owner',IDENTITY_PASSKEY_ENABLED:'true',IDENTITY_GOOGLE_ENABLED:'false',IDENTITY_MICROSOFT_ENABLED:'false',ADMIN_ACCESS_TEAM_DOMAIN:issuer,IDENTITY_ADMIN_ACCESS_AUD:audience,TURNSTILE_SITE_KEY:'fixture-site',TURNSTILE_SECRET_KEY:'fixture-secret',OWNER_EMAIL:'owner@example.test'};
let unexpectedOutbound=0;
const mfOptions={modules:[{type:'ESModule',path:resolve('dist/server/index.js')},...readdirSync('dist/server',{recursive:true}).filter(p=>p.endsWith('.js')&&p!=='index.js').map(p=>({type:'ESModule',path:resolve('dist/server',p)}))],modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:settings,cf:false,outboundService:async request=>{
 const url=new URL(request.url);if(url.href===issuer+'/cdn-cgi/access/certs')return Response.json({keys:[jwk]});
 if(url.href==='https://challenges.cloudflare.com/turnstile/v0/siteverify'){const b=await request.json();return Response.json({success:b.secret==='fixture-secret'&&b.response==='synthetic-challenge',hostname:domain,action:'account'});}
 unexpectedOutbound++;return new Response('Unexpected synthetic outbound',{status:502});
}};
const mf=new Miniflare(mfOptions);
let checks=0;const check=(value,label)=>{assert.ok(value,label);checks++;};
const request=(host,path='/identity/api',body,headers={})=>mf.dispatchFetch('https://'+host+path,{redirect:'manual',method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json',Origin:'https://'+host}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});
const browser=host=>({host,cookies:new Map(),csrf:'',access:null});
const saveCookies=(b,r)=>{for(const item of r.headers.getSetCookie()){const [name,...value]=item.split(';')[0].split('=');b.cookies.set(name,value.join('='));}};
const headers=b=>({Cookie:[...b.cookies].map(([k,v])=>k+'='+v).join('; '),...(b.access?{'cf-access-jwt-assertion':b.access}:{})});
async function context(b){const r=await request(b.host,'/identity/api',undefined,headers(b));saveCookies(b,r);const c=await r.json();if(r.status===200)b.csrf=c.csrf;return {r,c};}
async function post(b,body,extra={}){const r=await request(b.host,'/identity/api',body,{...headers(b),'x-identity-csrf':b.csrf,...extra});saveCookies(b,r);return r;}
const digest=v=>createHash('sha256').update(v).digest('hex');
try{
 const db=await mf.getD1Database('DB');
 for(const file of [...readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort().map(x=>'drizzle/'+x),...['AUTH','PRODUCT','SECURITY','BETA','ROUNDS','GUEST','AUTOPILOT','REWARDS','EARNING','REDEMPTION','PROFILE-EXPERIENCE','ADMIN-EXPERIENCE','IDENTITY'].map(x=>x+'-SCHEMA.sql')])await db.exec(readFileSync(file,'utf8').replace(/--> statement-breakpoint/g,'').replace(/^--.*$/gm,'').replace(/\n/g,' '));
 const password='Synthetic worker password 13579',salt='12345678901234567890123456789012',hash='scrypt$16384$8$5$'+salt+'$'+scryptSync(password,salt,32,{N:16384,r:8,p:5,maxmem:32*1024*1024}).toString('hex');
 await db.prepare("INSERT INTO members(id,email,name,role,debt,credit) VALUES('owner','owner@example.test','Owner','admin',0,0),('second-admin','second@example.test','Second admin','admin',0,0),('member','member@example.test','Member','member',725,250)").run();
 await db.prepare("INSERT INTO settings(id) VALUES('main')").run();
 for(const id of ['owner','second-admin','member'])await db.prepare('INSERT INTO auth_credentials VALUES(?,?,?)').bind(id,hash,Date.now()).run();
 for(const path of ['/','/about','/privacy']){
  const publicPage=await request(domain,path),html=await publicPage.text();
  check(publicPage.status===200&&!publicPage.headers.has('location')&&html.includes('IYAAYASFW member login'),'public branding page loads without a session or redirect: '+path);
  check(!html.includes('owner@example.test')&&!html.includes('member@example.test')&&!html.includes('Your balance'),'public page does not render member account data: '+path);
 }
 check((await request(domain,'/api/pilot')).status===401,'public homepage does not unlock store API');
 const rootHtml=await (await request(domain,'/')).text();
 check(rootHtml.includes('Why we request Google account information')&&rootHtml.includes('Member sign-in')&&!rootHtml.includes('mobile-bag'),'anonymous root explains the app without rendering the store');
 const entry=await request(domain,'/login?next=/products/synthetic-item'),entryLocation=new URL(entry.headers.get('location'));
 check(entry.status===303&&entryLocation.origin==='https://auth.test.local'&&entryLocation.pathname==='/identity','default login goes directly to the auth host');
 const destinationCookie=entry.headers.get('set-cookie');
 check(destinationCookie.startsWith('__Host-identity-destination=')&&destinationCookie.includes('Secure')&&destinationCookie.includes('HttpOnly')&&!destinationCookie.includes('Domain='),'direct login keeps a secure host-only return binding');
 const entryFlow=await db.prepare('SELECT * FROM identity_flows WHERE id=?').bind(entryLocation.searchParams.get('flow')).first();
 check(entryFlow.purpose==='login'&&entryFlow.audience==='member'&&entryFlow.member_id===null&&entryFlow.return_path==='/products/synthetic-item','login entry creates only anonymous member flow and preserves product return');
 check(entryFlow.destination_browser===digest(destinationCookie.split(';')[0].split('=')[1]),'auth handoff is bound to the member-host browser before choosing a method');
 const entryAuth=browser('auth.test.local');await context(entryAuth);
 const adoptedEntry=await post(entryAuth,{action:'adopt',flow:entryFlow.id}),entryView=(await adoptedEntry.json()).flow;
 check(adoptedEntry.status===200&&entryView.purpose==='login'&&entryView.returnPath==='/products/synthetic-item','auth chooser adopts direct login and preserves the password fallback return');
 const unsafeEntry=await request(domain,'/login?next=https://evil.test'),unsafeFlow=new URL(unsafeEntry.headers.get('location')).searchParams.get('flow');
 check((await db.prepare('SELECT return_path FROM identity_flows WHERE id=?').bind(unsafeFlow).first()).return_path==='/','login entry rejects external return destinations');
 check((await request(domain,'/login?password=1')).status===200,'explicit existing-password fallback stays available');
 const authLanding=await request('auth.test.local','/identity');
 check(authLanding.status===303&&new URL(authLanding.headers.get('location')).origin==='https://test.local','direct auth visit first establishes the member-host return binding');
 check((await request('auth.test.local','/identity?error=provider-verification')).status===200,'provider error remains readable without a redirect loop');
 for(const [id,sub,isOwner] of [['owner','owner-subject',1],['second-admin','second-subject',0]])await db.prepare('INSERT INTO identity_admin_principals(id,issuer,subject,member_id,identity_owner,provisioned_at,evidence) VALUES(?,?,?,?,?,?,?)').bind('p-'+id,issuer,sub,id,isOwner,Date.now(),'synthetic signed fixture').run();
 check((await request('unknown.test')).status===421,'unknown host denied');
 for(const host of ['auth.test.local','register.test.local'])for(const path of ['/api/pilot','/api/auth','/api/export','/api/history','/api/transactions','/api/community','/api/operations','/api/roadmap','/api/profile-images','/api/product-images','/api/admin/access'])check([404,405].includes((await request(host,path)).status),'legacy API isolated: '+host+path);
 const member=browser(domain);const ctx=await context(member);check(ctx.r.status===200&&ctx.c.methods.passkey,'identity context is available');
 const cookie=ctx.r.headers.get('set-cookie');check(cookie.includes('Secure')&&cookie.includes('HttpOnly')&&cookie.includes('SameSite=Lax')&&!/;\s*Domain=/i.test(cookie),'identity cookie is secure and host-only');
 check((await post(member,{action:'start'},{Origin:'https://evil.test'})).status===403,'cross-origin mutation rejected');
 check((await post(member,{action:'start'},{'x-identity-csrf':'wrong'})).status===403,'wrong CSRF rejected');
 check((await request(domain,'/api/auth',{action:'login',email:'member@example.test',password,challengeToken:'synthetic-challenge'})).status===403,'legacy mutation also requires identity CSRF');
 const login=await request(domain,'/api/auth',{action:'login',email:'member@example.test',password,challengeToken:'synthetic-challenge'},{...headers(member),'x-identity-csrf':member.csrf});saveCookies(member,login);check(login.status===200,'legacy password remains usable');await context(member);
 const signedHome=await request(domain,'/',undefined,headers(member)),signedHtml=await signedHome.text();
 check(signedHome.status===200&&signedHtml.includes('Email the store team')&&!signedHtml.includes('Why we request Google account information'),'signed-in root still renders the store');
 const signedEntry=await request(domain,'/login?next=/products/synthetic-item',undefined,headers(member));
 check(signedEntry.status===303&&signedEntry.headers.get('location')==='https://test.local/products/synthetic-item'&&!signedEntry.headers.has('set-cookie'),'signed-in member keeps the requested page without a new identity flow');
 const own=await post(member,{action:'account'});check(own.status===200&&(await own.json()).hasPassword,'existing account preserved');
 check((await context(member)).c.management===null,'ordinary member gets no management navigation');
 check((await post(member,{action:'importTemplate'})).status===403,'ordinary member cannot export roster template');
 const ownerMember=browser(domain);await context(ownerMember);
 const ownerLogin=await request(domain,'/api/auth',{action:'login',email:'owner@example.test',password,challengeToken:'synthetic-challenge'},{...headers(ownerMember),'x-identity-csrf':ownerMember.csrf});saveCookies(ownerMember,ownerLogin);
 const ownerContext=await context(ownerMember);
 check(ownerContext.c.management.href==='https://admin.test.local/?view=admin','owner Manage points to administrator host');
 for(const path of ['/?view=admin','/api/admin/access']){
  const redirect=await request(domain,path,undefined,headers(ownerMember));
  check(redirect.status===303&&redirect.headers.get('location')==='https://admin.test.local/?view=admin','legacy owner management entry migrates to admin host: '+path);
 }
 const memberPilot=await (await request(domain,'/api/pilot',undefined,headers(ownerMember))).json();
 check(!memberPilot.admin,'owner member-host session cannot read administrator dashboard');
 const flowResponse=await post(member,{action:'start',purpose:'add:passkey',next:'//evil.test'}),flowResult=await flowResponse.json();check(flowResponse.status===200&&flowResult.next.startsWith('https://register.test.local/identity?flow='),'fresh addition begins at fixed registration host');
 const flowId=new URL(flowResult.next).searchParams.get('flow'),register=browser('register.test.local'),auth=browser('auth.test.local');await context(register);await context(auth);
 check((await post(register,{action:'adopt',flow:flowId})).status===200,'registration browser binds before proof');
 check((await post(register,{action:'continueFresh',flow:flowId})).status===200,'fresh proof sends browser to auth');
 const adopted=await post(auth,{action:'adopt',flow:flowId}),freshView=(await adopted.json()).flow;
 check(adopted.status===200,'auth browser binds');
 check(freshView.hasPassword&&freshView.freshMethods.length===0,'fresh verification offers only the existing password for an unlinked member');
 check((await post(auth,{action:'provider',flow:flowId,method:'google'})).status===403,'unlinked Google cannot start fresh verification');
 check((await post(auth,{action:'passkeyOptions',flow:flowId})).status===403,'unlinked passkey cannot start fresh verification');
 check((await db.prepare('SELECT count(*) n FROM identity_ceremonies WHERE flow_id=?').bind(flowId).first()).n===0,'rejected unlinked choices create no external ceremony');
 const other=browser('auth.test.local');await context(other);check((await post(other,{action:'adopt',flow:flowId})).status===403,'another auth browser cannot adopt flow');
 const proof=await post(auth,{action:'passwordProof',flow:flowId,password}),proofBody=await proof.json();check(proof.status===200,'fresh existing password accepted');
 const fragment=new URLSearchParams(new URL(proofBody.next).hash.slice(1));
 const completion=await post(member,{action:'complete',flow:flowId,code:fragment.get('code')}),completed=await completion.json();check(completion.status===200&&completed.next.startsWith('https://register.test.local/identity?flow='),'fresh grant hands off to registration');
 check(completion.headers.getSetCookie().some(c=>c.startsWith('__Host-identity-destination=')&&!c.includes('Max-Age=0')),'destination binding retained through enrollment');
 const nextFlow=new URL(completed.next).searchParams.get('flow');check((await post(register,{action:'adopt',flow:nextFlow})).status===200,'new enrollment retains original registration browser');
 const options=await post(register,{action:'passkeyOptions',flow:nextFlow});const registrationOptions=await options.json();check(options.status===200&&registrationOptions.options.rp.id===domain&&registrationOptions.options.authenticatorSelection.userVerification==='required','real Worker emits RP-bound UV-required registration options');
 // A second tab must not replace the method the member reviewed before confirmation.
 const syntheticProof=JSON.stringify({kind:'passkey',credentialId:'reviewed-synthetic-id',publicKey:'synthetic',counter:0,userHandle:'synthetic',rpId:domain});
 await db.prepare('UPDATE identity_flows SET proof=? WHERE id=?').bind(syntheticProof,nextFlow).run();
 const reviewed=await (await post(register,{action:'flow',flow:nextFlow})).json();
 check(reviewed.flow.proofId===digest(syntheticProof),'confirmation exposes a digest of the reviewed method');
 await db.prepare('UPDATE identity_flows SET proof=? WHERE id=?').bind(syntheticProof.replace('reviewed-synthetic-id','replacement-synthetic-id'),nextFlow).run();
 check((await post(register,{action:'finishEnrollment',flow:nextFlow,proofId:reviewed.flow.proofId})).status===409,'changed enrollment proof requires another explicit review');
 check((await db.prepare("SELECT count(*) n FROM identity_credentials WHERE member_id='member'").first()).n===0,'stale confirmation creates no credential');
 check((await post(member,{action:'complete',flow:flowId,code:fragment.get('code')})).status===409,'handoff replay denied');
 const admin=browser('admin.test.local');check((await context(admin)).r.status===403,'admin requires Access before app login');
 admin.access=await token('unmapped');check((await context(admin)).r.status===403,'valid but unmapped Access subject denied');
 admin.access=await token('owner-subject',Math.floor(Date.now()/1000)-1900);check((await context(admin)).r.status===403,'expired Access factor denied');
 admin.access=await token('owner-subject',undefined,'wrong-audience');check((await context(admin)).r.status===403,'wrong Access audience denied');
 admin.access=await token();check((await context(admin)).r.status===200,'mapped current Access subject accepted');
 const enterAdmin=await post(admin,{action:'adminLogin',section:'identity'});
 check(enterAdmin.status===200&&(await enterAdmin.json()).next==='/?view=admin&section=identity','admin app session preserves account-management destination');await context(admin);
 check((await post(admin,{action:'adminRead',query:''})).status===200,'owner identity workspace available');
 const template=await post(admin,{action:'importTemplate'}),templateBody=await template.json();
 check(template.status===200&&templateBody.csv.includes('"member",,,,,')&&!templateBody.csv.includes('member@example.test'),'owner roster template uses explicit IDs without inferred email authority');
 const blankPreview=await post(admin,{action:'importPreview',csv:templateBody.csv});
 check(blankPreview.status===200&&(await blankPreview.json()).rows.every(row=>row.status==='Unchanged'),'blank roster template previews without granting or changing access');
 const newTemplate=await post(admin,{action:'importTemplate',mode:'create'}),newTemplateBody=await newTemplate.json();
 check(newTemplate.status===200&&newTemplateBody.csv.includes('email')&&!newTemplateBody.csv.includes('member_id')&&newTemplateBody.filename.endsWith('.csv'),'new-member download supplies headings without existing records');
 const newCsv=newTemplateBody.csv+'New Member,new-member@example.test,,new-member@gmail.com,TRUE\r\n';
 const newPreviewResponse=await post(admin,{action:'importPreview',mode:'create',csv:newCsv}),newPreview=await newPreviewResponse.json();
 check(newPreviewResponse.status===200&&newPreview.rows[0].status==='Create'&&newPreview.rows[0].grants[0].provider==='google','new CSV previews creation and explicit Google grant');
 check(!(await db.prepare("SELECT 1 FROM members WHERE email='new-member@example.test'").first()),'HTTP preview does not create a member');
 check((await post(admin,{action:'importReview',batch:newPreview.batch,hash:newPreview.hash})).status===200,'owner can recover preview details');
 check((await post(member,{action:'importReview',batch:newPreview.batch,hash:newPreview.hash})).status===403,'member cannot read owner preview');
 check((await post(admin,{action:'importPreview',mode:'upsert',csv:newCsv})).status===400,'unknown importer mode rejected');
 check((await post(admin,{action:'importPreview',mode:'create',csv:'display_name,email,access_enabled,role\nBad,bad@example.test,TRUE,admin'})).status===400,'HTTP creation rejects privileged columns');
 check((await post(admin,{action:'admin',approval:'unverified',payload:{operation:'importCommit',batch:newPreview.batch,hash:newPreview.hash,rows:[1]}})).status===403,'HTTP create requires fresh exact-action proof');
 const escapedCell='"'+'\\'.repeat(120)+'"',escapedCsv='display_name,email,contact_email,google_bootstrap_email,access_enabled\n'+Array.from({length:100},()=>['"'+'""'.repeat(80)+'"',escapedCell,escapedCell,escapedCell,'TRUE'].join(',')).join('\n');
 check(Buffer.byteLength(escapedCsv)<65536&&Buffer.byteLength(JSON.stringify({action:'importPreview',mode:'create',csv:escapedCsv}))>70000,'fixture covers CSV-to-JSON expansion');
 check((await post(admin,{action:'importPreview',mode:'create',csv:escapedCsv})).status===200,'valid-size CSV reaches row validation despite JSON escaping overhead');
 const second=browser('admin.test.local');second.access=await token('second-subject');await context(second);await post(second,{action:'adminLogin'});await context(second);
 check((await context(second)).c.management.identityHref===null,'commerce-only administrator is not offered owner-only account tools');
 check((await post(second,{action:'adminRead',query:''})).status===403,'second commerce administrator cannot grant new identities');
 check((await post(second,{action:'importTemplate'})).status===403,'second commerce administrator cannot export identity template');
 check((await request(second.host,'/api/pilot',undefined,headers(second))).status===200,'second administrator retains commerce access');
 check((await request(domain,'/api/pilot',undefined,{Cookie:'__Host-supply-session='+admin.cookies.get('__Host-supply-admin')})).status===401,'admin token cannot be replayed as member token');
 check((await request(admin.host,'/api/pilot',undefined,{...headers(admin),'cf-access-jwt-assertion':second.access})).status===403,'Access principal must match app session');
 const state=await db.prepare("SELECT debt,credit FROM members WHERE id='member'").first();check(state.debt===725&&state.credit===250,'identity checks preserve balances');
 await mf.setOptions({...mfOptions,bindings:{...settings,IDENTITY_ROLLOUT:'owner-smoke'}});
 const ownerStageContext=await context(ownerMember);
 check(ownerStageContext.c.management.href==='https://admin.test.local/?view=admin','owner-stage navigation also uses administrator host');
 const ownerStageRoute=await request(domain,'/?view=admin&section=identity',undefined,headers(ownerMember));
 check(ownerStageRoute.status===303&&ownerStageRoute.headers.get('location')==='https://admin.test.local/?view=admin&section=identity','owner-stage server redirect preserves account suite');
 check(!(await (await request(domain,'/api/pilot',undefined,headers(ownerMember))).json()).admin,'owner-stage member session has no administrator dashboard authority');
 check(unexpectedOutbound===0,'no production/provider traffic sent');
 const result={suite:'identity-http',checks,providers:'synthetic',mfa:'signed fixture only',runtime:'compiled Worker and isolated D1',passedAt:new Date().toISOString()};writeFileSync('.sites-runtime/identity-http-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await mf.dispose();}
