import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
const out=path.resolve('.sites-runtime/pilot-tests');fs.mkdirSync(out,{recursive:true});
for(const name of ['catalog','owner','service']){const source=fs.readFileSync(`lib/pilot/${name}.ts`,'utf8');const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replaceAll("'./catalog'","'./catalog.mjs'").replaceAll("'./owner'","'./owner.mjs'");fs.writeFileSync(`${out}/${name}.mjs`,code)}
fs.writeFileSync(`${out}/owner.mjs`,"export const OWNER_EMAIL='owner@example.test';");
const {mutate,readState}=await import(`${out}/service.mjs`);const {OWNER_EMAIL}=await import(`${out}/owner.mjs`);
const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8'));
sqlite.exec(fs.readFileSync('AUTH-SCHEMA.sql','utf8'));
class Statement{constructor(sql,v=[]){this.sql=sql;this.v=v}bind(...v){return new Statement(this.sql,v)}async first(){return sqlite.prepare(this.sql).get(...this.v)||null}async all(){return{results:sqlite.prepare(this.sql).all(...this.v)}}async run(){return sqlite.prepare(this.sql).run(...this.v)}}
const db={prepare:sql=>new Statement(sql),batch:async statements=>{sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const owner={userId:'owner-user',email:OWNER_EMAIL},user={userId:'test-member',email:'pilot@example.test'};let checks=0;
const check=(v,m)=>{assert.ok(v,m);checks++};
const send=(u,b)=>mutate(db,u,{requestId:crypto.randomUUID(),...b});
const state=()=>readState(db,owner);
const product=async(id='monster')=>(await state()).products.find(p=>p.id===id);
const order=(method,qty=1,id=crypto.randomUUID(),productId='monster',price=250)=>({action:'order',id,method,items:[{id:productId,qty,price}]});
const configure=async(id,stock=20,category='Drinks',preorder=false)=>{const p=await product(id);await send(owner,{action:'product',id,name:p.name,category,detail:p.detail,price:250,cost:100,taxBp:0,stock,previousStock:p.stock,version:p.version,reorder:3,active:true,preorder,reason:'Verified test count'})};
check((await state()).member.role==='admin','Owner becomes administrator');
await assert.rejects(()=>send(owner,order('cash')),/paused/);checks++;
await assert.rejects(()=>send(null,{action:'settings'}),/Member access/);checks++;
await configure('monster');await configure('coin',10,'Gear');
await send(owner,{action:'settings',cashtag:'PilotExample',cashInstructions:'Cash box',enabled:true,reminderDays:7});
const cash=order('cash');await send(owner,cash);check((await product()).stock===19,'Member cash records stock');await send(owner,cash);check((await product()).stock===19,'Duplicate consumption is idempotent');
check((await state()).admin.payments[0].status==='pending','Member cash is unverified');
await assert.rejects(()=>send(owner,{...cash,items:[{id:'monster',qty:2,price:250}]}),/already been used/);checks++;
await assert.rejects(()=>send(null,order('cash',1,crypto.randomUUID(),'coin')),/Member access/);checks++;
await send(owner,{action:'member',name:'Pilot Member',email:user.email,debt:0,credit:0,tabLimit:2000,active:true,reason:'Opening test balance'});
check((await readState(db,user)).member.user_id===user.userId,'Invitation binds to authenticated stable identity');
await send(user,order('tab',4));check((await readState(db,user)).member.debt===1000,'Tab records debt');const beforeLimit=(await product()).stock;
await assert.rejects(()=>send(user,order('tab',5)),/record changed/);checks++;check((await product()).stock===beforeLimit,'Over-limit batch rolls stock back');
const settlement={action:'payment',id:crypto.randomUUID(),method:'cashapp',purpose:'settlement',amount:400};await send(user,settlement);check((await readState(db,user)).member.debt===1000,'Reported settlement leaves debt unchanged');
const salesBefore=(await state()).admin.orders.reduce((s,o)=>s+o.total,0);
const verify={action:'verify',id:settlement.id,confirmed:true,reference:'transfer-001'};await send(owner,verify);await send(owner,verify);
check((await readState(db,user)).member.debt===600,'Confirmed settlement applied exactly once');check((await state()).admin.orders.reduce((s,o)=>s+o.total,0)===salesBefore,'Settlement does not create revenue');
const topup={action:'payment',id:crypto.randomUUID(),method:'cashapp',purpose:'topup',amount:500};await send(user,topup);check((await readState(db,user)).member.credit===0,'Unconfirmed credit cannot be spent');
await assert.rejects(()=>send(owner,{action:'verify',id:topup.id,confirmed:true,reference:'transfer-001'}),/already recorded/);checks++;check((await readState(db,user)).member.credit===0,'Duplicate payment reference rolls credit back');
await send(owner,{action:'verify',id:topup.id,confirmed:true,reference:'transfer-002'});await send(user,order('credit'));check((await readState(db,user)).member.credit===250,'Credit purchase deducts balance');
const stale=await product();await send(owner,order('cash'));
await assert.rejects(()=>send(owner,{action:'product',id:'monster',name:stale.name,category:stale.category,detail:'',price:250,cost:100,taxBp:0,stock:stale.stock,previousStock:stale.stock,version:stale.version,reorder:3,active:true,preorder:false,reason:'Stale count'}),/record changed/);checks++;
const receive={action:'receive',requestId:crypto.randomUUID(),id:'monster',qty:24,amount:2400,reference:'Costco test receipt'};const beforeReceive=(await product()).stock;await send(owner,receive);await send(owner,receive);check((await product()).stock===beforeReceive+24,'Restock retries do not duplicate stock');
const pending2={action:'payment',id:crypto.randomUUID(),method:'cash',purpose:'settlement',amount:600};await send(user,pending2);await assert.rejects(()=>send(user,{...pending2,id:crypto.randomUUID(),amount:1}),/record changed/);checks++;
const beforeVoid=(await product()).stock;await send(owner,{action:'reject',id:cash.id,reason:'Items returned',returned:true});check((await product()).stock===beforeVoid+1,'Void restores stock once');await assert.rejects(()=>send(owner,{action:'reject',id:cash.id,reason:'Items returned',returned:true}),/pending payment/);checks++;
await configure('monster',1);const firstOrder=order('cash'),secondOrder=order('cash');await send(owner,firstOrder);await assert.rejects(()=>send(owner,secondOrder),/insufficient stock/);checks++;check((await product()).stock===0,'Stock cannot go negative');
await assert.rejects(()=>send(user,order('tab',1,crypto.randomUUID(),'coin')),/paid upfront/);checks++;
await assert.rejects(()=>readState(db,null),/Member access/);checks++;
const memberData=await readState(db,user);check(!memberData.admin&&memberData.products.every(p=>p.cost===undefined),'Member cannot read management records or costs');
check((await state()).admin.events.length>10,'Audit trail persists');
console.log(`PASS: ${checks} financial, inventory, access, and idempotency checks.`);
