import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
const out=path.resolve('.sites-runtime/rounds34-tests');
for(const f of fs.readdirSync('lib',{recursive:true}).filter(f=>f.endsWith('.ts'))){const dest=path.join(out,'lib',f.replace(/\.ts$/,'.mjs'));fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,ts.transpileModule(fs.readFileSync(path.join('lib',f),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from (["'])(\.{1,2}\/[^"']+)\1/g,'from "$2.mjs"'))}
fs.writeFileSync(out+'/lib/pilot/owner.mjs',"export const OWNER_EMAIL='owner@example.test';");
const {changeEmail,emailChanges}=await import(out+'/lib/pilot/email-changes.mjs');
const {mutateInitiative,initiativePage}=await import(out+'/lib/pilot/initiatives.mjs');
const {taskPage,updateTask}=await import(out+'/lib/pilot/tasks.mjs');
const {passwordHash,digest}=await import(out+'/lib/auth/password.mjs');
const {mutateCommunity}=await import(out+'/lib/pilot/community.mjs');
const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');
for(const f of ['drizzle/0000_tiny_shape.sql','drizzle/0001_absent_guardsmen.sql','AUTH-SCHEMA.sql','PRODUCT-SCHEMA.sql','SECURITY-SCHEMA.sql','BETA-SCHEMA.sql'])sqlite.exec(fs.readFileSync(f,'utf8'));
const run=(s,...v)=>sqlite.prepare(s).run(...v),get=(s,...v)=>sqlite.prepare(s).get(...v);
run("INSERT INTO settings(id,enabled) VALUES('main',1)");
const users={};for(const [id,role]of[['owner','admin'],['admin','admin'],['buyer','member'],['gear','member']]){run('INSERT INTO members(id,user_id,email,name,role,debt,credit) VALUES(?,?,?,?,?,?,?)',id,id,id+'@example.test',id,role,id==='buyer'?2100:0,id==='buyer'?700:0);users[id]={...get('SELECT * FROM members WHERE id=?',id),posting_enabled:1};}
run("INSERT INTO member_access(member_id,snacks,gear) VALUES('gear',0,1)");
const snapshot=JSON.stringify(sqlite.prepare('SELECT * FROM members').all());for(let n=0;n<2;n++)sqlite.exec(fs.readFileSync('ROUNDS-SCHEMA.sql','utf8'));
let checks=0;const ok=(x,n)=>{assert.ok(x,n);checks++},bad=async(f,re)=>{await assert.rejects(f,re);checks++};
ok(JSON.stringify(sqlite.prepare('SELECT * FROM members').all())===snapshot,'repeat migration preserves all members and balances');
class S{constructor(sql,v=[]){this.sql=sql;this.v=v}bind(...v){return new S(this.sql,v)}async first(){return get(this.sql,...this.v)||null}async all(){return{results:sqlite.prepare(this.sql).all(...this.v)}}async run(){const r=run(this.sql,...this.v);return{meta:{changes:r.changes}}}}
const db={prepare:s=>new S(s),batch:async ss=>{sqlite.exec('BEGIN');try{const r=ss.map(s=>run(s.sql,...s.v));sqlite.exec('COMMIT');return r}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const body=b=>({requestId:crypto.randomUUID(),...b}),email=(u,b)=>changeEmail(db,users[u],body(b)),community=(u,b)=>mutateCommunity(db,users[u],body(b)),activity=(u,b)=>mutateInitiative(db,users[u],body(b));
const pass='this-is-a-very-long-test-password';run('INSERT INTO auth_credentials(member_id,password_hash,updated_at) VALUES(?,?,?)','buyer',await passwordHash(pass),Date.now());
await bad(()=>email('buyer',{action:'emailRequest',email:'new@example.test',confirmEmail:'new@example.test',password:'wrong'}),/password/);
const request=await email('buyer',{action:'emailRequest',email:'NEW@example.test',confirmEmail:'new@example.test',password:pass}),eid=request.id;
ok(get('SELECT new_email FROM email_change_requests WHERE id=?',eid).new_email==='new@example.test','email normalized');
const er=()=>get('SELECT * FROM email_change_requests WHERE id=?',eid);
await bad(()=>email('buyer',{action:'emailCode',id:eid,version:0}),/administrator/);
await bad(()=>email('owner',{action:'emailApprove',id:eid,version:0,note:'Checked user'}),/Verify/);
const code=await email('owner',{action:'emailCode',id:eid,version:0});ok(er().code_hash!==code.code&&er().code_hash===digest(code.code),'only hash stored');
const wrong=body({action:'emailVerify',id:eid,version:er().version,code:'wrong'});await bad(()=>changeEmail(db,users.buyer,wrong),/not recognized/);await bad(()=>changeEmail(db,users.buyer,wrong),/not recognized/);ok(er().attempts===1,'same failed request does not consume attempts twice');
await bad(()=>email('gear',{action:'emailVerify',id:eid,version:er().version,code:code.code}),/unavailable/);
await email('buyer',{action:'emailVerify',id:eid,version:er().version,code:code.code});ok(er().status==='ready_for_review'&&!er().code_hash,'verified code cleared');
await email('owner',{action:'emailApprove',id:eid,version:er().version,note:'Verified identity with member'});ok(get("SELECT email FROM members WHERE id='buyer'").email==='buyer@example.test','approval does not change login');
await bad(()=>email('owner',{action:'emailComplete',id:eid,version:er().version,note:'Updated policy'}),/three/);
run("INSERT INTO auth_sessions(token_hash,member_id,created_at,expires_at) VALUES('buyer-session','buyer',?,?)",Date.now(),Date.now()+100000);
await email('owner',{action:'emailComplete',id:eid,version:er().version,note:'Updated each applicable Access policy',newAddressAllowed:true,oldAddressRemoved:true,identityChecked:true});
ok(er().status==='completed','completed after checklist');ok(get("SELECT email FROM members WHERE id='buyer'").email==='new@example.test','address changed');ok(get("SELECT debt,credit FROM members WHERE id='buyer'").debt===2100&&get("SELECT credit FROM members WHERE id='buyer'").credit===700,'balances preserved');ok(get("SELECT COUNT(*) n FROM auth_sessions WHERE member_id='buyer'").n===0,'sessions revoked');ok(get("SELECT COUNT(*) n FROM member_email_history WHERE member_id='buyer'").n===1,'identity history retained');
ok(!(await emailChanges(db,users.gear)).records.length,'member sees own requests only');
await bad(()=>email('admin',{action:'emailAdminRequest',memberId:'owner',email:'other@example.test',confirmEmail:'other@example.test'}),/owner email/);
await bad(()=>email('admin',{action:'emailAdminRequest',memberId:'admin',email:'other@example.test',confirmEmail:'other@example.test'}),/Only the owner/);
let inbox=await taskPage(db,users.owner,{filter:'open'});ok(inbox.records.some(t=>t.task_key==='tab:buyer'),'tab soft cap creates task');ok(!inbox.records.some(t=>t.task_key==='email:'+eid),'completed email clears open queue');
await bad(()=>taskPage(db,users.buyer,{}),/administrator/);
await bad(()=>updateTask(db,users.owner,body({action:'taskUpdate',taskKey:'tab:buyer',version:-1,state:'resolved',note:'Attempt to clear balance'})),/linked action/);
await updateTask(db,users.owner,body({action:'taskUpdate',taskKey:'tab:buyer',version:-1,state:'in_progress',assignee:'admin',note:'Ask about pending cash payment'}));
await bad(()=>updateTask(db,users.owner,body({action:'taskUpdate',taskKey:'tab:buyer',version:-1,state:'open',note:'stale version change'})),/changed/);
await updateTask(db,users.owner,body({action:'tabReminder',taskKey:'tab:buyer',note:'Spoke with member at the store'}));run("UPDATE members SET debt=0 WHERE id='buyer'");inbox=await taskPage(db,users.owner,{filter:'resolved',taskKey:'tab:buyer'});ok(inbox.task.status==='resolved'&&inbox.events.length===2,'underlying settlement resolves task and retains notes/reminder');
const rbody=body({action:'requestCreate',shop:'snacks',title:'Test granola bars',body:'A simple new snack.'});await mutateCommunity(db,users.buyer,rbody);
const trial=await activity('owner',{action:'initiativeCreate',requestIdSource:rbody.requestId,version:0,kind:'trial',category:'Snacks',endsAt:Date.now()+86400000,note:'A one-day sample trial.'});
const ir=()=>get('SELECT * FROM product_initiatives WHERE id=?',trial.id);ok(ir().state==='draft'&&get('SELECT active FROM products WHERE id=?',trial.productId).active===0,'conversion creates draft only');
await bad(()=>activity('owner',{action:'initiativeCreate',requestIdSource:rbody.requestId,version:1,kind:'trial',category:'Snacks',endsAt:Date.now()+86400000,note:'Duplicate trial attempt'}),/changed/);
await bad(()=>activity('owner',{action:'initiativeOpen',id:trial.id,version:0}),/Configure/);
run('UPDATE products SET active=1,price=100,cost=40,tax_bp=0,stock=10 WHERE id=?',trial.productId);
await activity('owner',{action:'initiativeOpen',id:trial.id,version:0});ok(ir().state==='open','trial opens after product ready');
await bad(()=>initiativePage(db,users.gear,{shop:'snacks'}),/not available/);
await bad(()=>activity('buyer',{action:'trialFeedback',id:trial.id,version:1,keep:1}),/purchase/);
run("INSERT INTO orders(id,code,fingerprint,member_id,payer,method,status,total,tax,cost,created_at) VALUES('sale','S-TEST','x','buyer','Buyer','tab','tab',200,0,80,?)",Date.now());run("INSERT INTO order_items(id,order_id,product_id,name,qty,price,cost,tax_bp,preorder) VALUES('line','sale',?,'Granola',2,100,40,0,0)",trial.productId);
await activity('buyer',{action:'trialFeedback',id:trial.id,version:1,keep:1});await activity('buyer',{action:'trialFeedback',id:trial.id,version:1,keep:0});ok(get('SELECT COUNT(*) n FROM trial_feedback').n===1,'one editable trial feedback');
await activity('owner',{action:'initiativeLoss',id:trial.id,version:1,qty:2,kind:'waste',note:'Two damaged bars at receiving'});ok(get('SELECT stock FROM products WHERE id=?',trial.productId).stock===8,'recorded loss reduces stock once');
const report=(await initiativePage(db,users.owner,{shop:'snacks'},true)).records[0];ok(report.metrics.sales.units===2&&report.metrics.sales.known_cost===80&&report.metrics.losses.known_cost===80,'sales and losses report exact costs');
const publicReport=(await initiativePage(db,users.buyer,{shop:'snacks'})).records[0];ok(!('metrics'in publicReport)&&!('cost'in publicReport),'member cannot see operating costs');
await activity('owner',{action:'initiativeDecide',id:trial.id,version:1,state:'discontinued',note:'Not enough demand to keep this item'});ok(!get('SELECT active FROM products WHERE id=?',trial.productId).active&&get("SELECT total FROM orders WHERE id='sale'").total===200,'discontinue hides without changing sales');
const gearRequest=body({action:'requestCreate',shop:'gear',title:'New unit hoodie',body:'Navy with a small patch.'});await mutateCommunity(db,users.gear,gearRequest);
const interest=await activity('owner',{action:'initiativeCreate',requestIdSource:gearRequest.requestId,version:0,kind:'interest',endsAt:Date.now()+86400000,note:'Tell us your size and quantity'});
run("INSERT INTO product_variants(id,product_id,label,size,stock) VALUES('medium',?,'Medium','M',0)",interest.productId);
await activity('owner',{action:'initiativeOpen',id:interest.id,version:0});
await bad(()=>activity('gear',{action:'interestSave',id:interest.id,version:1,qty:2,optionId:'wrong'}),/option/);
await activity('gear',{action:'interestSave',id:interest.id,version:1,qty:2,optionId:'medium'});await activity('gear',{action:'interestSave',id:interest.id,version:1,qty:3,optionId:'medium'});
ok(get('SELECT COUNT(*) n FROM initiative_interest').n===1&&get('SELECT qty FROM initiative_interest').qty===3,'editable per-option demand');ok(get("SELECT COUNT(*) n FROM orders").n===1,'interest creates no orders');
await bad(()=>activity('owner',{action:'initiativePreorder',id:interest.id,version:1,note:'Launch preorder now'}),/Gear Manager/);
run('UPDATE products SET active=1,price=3000,tax_bp=0,preorder=1 WHERE id=?',interest.productId);run("UPDATE product_variants SET preorder=1 WHERE id='medium'");await activity('owner',{action:'initiativePreorder',id:interest.id,version:1,note:'Preorders open for pickup'});
ok(get('SELECT product_id,state FROM product_initiatives WHERE id=?',interest.id).product_id===interest.productId,'preorder reuses linked product');ok(get('SELECT COUNT(*) n FROM initiative_interest').n===1,'preorder retains demand history');await bad(()=>activity('gear',{action:'interestSave',id:interest.id,version:2,qty:1,optionId:'medium'}),/closed/);
// Codes expire, lock after bounded attempts, and cannot collide with a current identity.
await bad(()=>email('owner',{action:'emailAdminRequest',memberId:'gear',email:'admin@example.test',confirmEmail:'admin@example.test'}),/cannot be used/);
const blocked=await email('owner',{action:'emailAdminRequest',memberId:'gear',email:'gear-new@example.test',confirmEmail:'gear-new@example.test'});
let bg=()=>get('SELECT * FROM email_change_requests WHERE id=?',blocked.id);
const bc=await email('owner',{action:'emailCode',id:blocked.id,version:bg().version});
run('UPDATE email_change_requests SET code_expires_at=? WHERE id=?',Date.now()-1,blocked.id);
await bad(()=>email('gear',{action:'emailVerify',id:blocked.id,version:bg().version,code:bc.code}),/fresh verification/);
const fresh=await email('owner',{action:'emailCode',id:blocked.id,version:bg().version});
for(let n=0;n<5;n++)await bad(()=>email('gear',{action:'emailVerify',id:blocked.id,version:bg().version,code:'incorrect'}),/not recognized/);
await bad(()=>email('gear',{action:'emailVerify',id:blocked.id,version:bg().version,code:fresh.code}),/fresh verification/);
await email('gear',{action:'emailCancel',id:blocked.id,version:bg().version});
ok(!bg().code_hash&&bg().status==='cancelled','cancelled request discards code');
// The write guard rechecks the target role after the initial read.
const promoted=await email('owner',{action:'emailAdminRequest',memberId:'gear',email:'promoted@example.test',confirmEmail:'promoted@example.test'});
const raced={...db,batch:async ss=>{run("UPDATE members SET role='admin' WHERE id='gear'");return db.batch(ss)}};
await bad(()=>changeEmail(raced,users.admin,body({action:'emailCode',id:promoted.id,version:0})),/changed/);
run("UPDATE members SET role='member' WHERE id='gear'");
// Reopen disposable initiative fixtures only, then check restrictions at both read and write boundaries.
run("UPDATE product_initiatives SET state='open',ends_at=? WHERE id=?",Date.now()+86400000,interest.id);
run("INSERT INTO member_controls(member_id,posting_enabled) VALUES('gear',0)");
await bad(()=>activity('gear',{action:'interestSave',id:interest.id,version:2,qty:4,optionId:'medium'}),/changed/);
run("UPDATE member_controls SET posting_enabled=1 WHERE member_id='gear'");
run('UPDATE item_requests SET removed=1 WHERE id=?',gearRequest.requestId);
ok(!(await initiativePage(db,users.gear,{shop:'gear'})).records.length,'removed source hides linked community activity');
await bad(()=>activity('gear',{action:'interestSave',id:interest.id,version:2,qty:4,optionId:'medium'}),/changed/);
run('UPDATE item_requests SET removed=0 WHERE id=?',gearRequest.requestId);
run('UPDATE product_initiatives SET ends_at=? WHERE id=?',Date.now()-1,interest.id);
await bad(()=>activity('gear',{action:'interestSave',id:interest.id,version:2,qty:4,optionId:'medium'}),/closed/);
await bad(()=>updateTask(db,users.owner,body({action:'taskUpdate',taskKey:'tab:buyer',version:0,state:'open',assignee:'buyer',note:'Invalid member assignee'})),/active administrator/);
const longSearch=await taskPage(db,users.owner,{search:'界'.repeat(80)});ok(!longSearch.records.length,'long literal search stays within platform pattern limits');
console.log(`Rounds 3–4: ${checks} checks passed.`);
sqlite.close();
