export const metadata={title:'Privacy policy | IYAAYASFW member login'};
export default function Privacy(){return <main className="identity-shell"><article className="panel identity-panel public-info">
 <a href="/about">IYAAYASFW member login</a><h1>Privacy policy</h1><p>Effective September 21, 2026.</p>
 <p>This policy describes information handled by IYAAYASFW member login and the IYAAYASFW Unit Supply snackbar and gear website. The service is operated privately for approved members and administered by the snackbar owner.</p>
 <h2>Information we collect</h2>
 <p>We keep an approved member ID, name, roster email, access permissions and any separate contact address you provide. Store records include orders, pickup details, payment reports, balances and corrections. Optional community, profile and rewards features store the information you submit and your related privacy preferences.</p>
 <p>When you choose Google or personal Microsoft, we request the openid, email and profile scopes. We receive a provider account identifier and available basic identity claims, such as email, verified-email status and profile name. We store the provider identifier and observed email to link the method to your existing membership. If enabled by the provider, an authentication timestamp helps verify sensitive account changes. We do not request your email messages, contacts, calendars or files, and we do not receive your Google or Microsoft password.</p>
 <p>Passkeys use a public key, credential identifier and authentication metadata. Private keys, device PINs and biometrics remain with your device or passkey provider. Existing snackbar passwords are stored as password hashes. Session and invitation records, rate-limit data, and security events help protect account access. Cloudflare processes connection information, including IP addresses, to host and secure the service.</p>
 <h2>How we use information</h2>
 <p>We use this information to authenticate approved members, link authorized sign-in methods, fulfill orders, maintain accurate store records, provide community features you choose, support recovery, and prevent abuse. Email or name similarity alone does not establish account ownership. Google account data is used for these user-facing access and support functions, not advertising or model training.</p>
 <h2>Access and service providers</h2>
 <p>Members can access their own account and records, plus community content permitted by the feature's audience and privacy settings. Authorized administrators can access the records needed to operate the store and resolve account issues. New identity authority is managed by the owner.</p>
 <p>Cloudflare hosts the application, database and images and provides security services. Google or Microsoft handles its own sign-in when you select that provider. An owner-controlled encrypted backup is kept for recovery. We do not sell member information or share it with advertising services. We may disclose information where required by law or to address abuse and protect the service.</p>
 <h2>Cookies and security</h2>
 <p>Necessary cookies maintain sign-in, bind verification to your browser and protect requests. Administrator access requires additional verification. Account changes require fresh proof; account recovery uses independently verified support or private invitations. Secrets and raw authentication tokens are excluded from application audit records.</p>
 <h2>Retention and deletion</h2>
 <p>Member and business records are retained to operate the store, reconcile transactions and resolve disputes; removing a sign-in method does not erase purchase or payment history. Unmatched login-request details are normally removed after 30 days, ended identity-session metadata after 90 days, and identity audit records after 365 days, unless retained for an incident. Temporary authentication secrets expire and are removed by scheduled cleanup. Encrypted backups may retain older records until the owner replaces or deletes those archives.</p>
 <h2>Your choices and support</h2>
 <p>You can inspect linked methods and sessions, sign out devices, and remove a method when another usable method remains. You may also revoke this app's access through Google or Microsoft account settings. Contact the snackbar administrator through your established unit contact channel or the support email on the Google consent screen to request access, correction, account closure or deletion. We will review what can be removed and explain any records retained for store accounting, security or dispute resolution.</p>
 <p>Provider services also apply their own privacy policies. We will update this page when our handling of information changes.</p>
 <nav className="identity-links"><a href="/about">About the app</a><a href="/login">Member sign-in</a></nav>
 </article></main>;}
