export const metadata={title:'Privacy policy | IYAAYASFW member login'};
export default function Privacy(){return <main className="identity-shell"><article className="panel identity-panel public-info">
 <a href="/about">IYAAYASFW member login</a><h1>Privacy policy</h1><p>Effective September 21, 2026.</p>
 <p>This policy describes information handled by IYAAYASFW member login and the IYAAYASFW Unit Supply snackbar and gear website at iyaayasfw.com. The service is operated privately for approved members and administered by the snackbar owner. This policy covers member sign-in, linked methods, store activity and account support.</p>
 <p>Privacy contact: the snackbar administrator at <a href="mailto:snackbar@iyaayasfw.com?subject=Privacy%20request">snackbar@iyaayasfw.com</a>. You may also use your established unit contact channel. You can read this policy without an account.</p>
 <h2>Information we collect</h2>
 <p>We keep an approved member ID, name, roster email, access permissions and any separate contact address you provide. Store records include orders, pickup details, payment reports, balances and corrections. Optional community, profile and rewards features store the information you submit and your related privacy preferences.</p>
 <p>Passkeys use a public key, credential identifier and authentication metadata. Private keys, device PINs and biometrics remain with your device or passkey provider. Existing snackbar passwords are stored as password hashes. Session and invitation records, rate-limit data, and security events help protect account access. Cloudflare processes connection information, including IP addresses, to host and secure the service.</p>
 <h2>Google user data: access and use</h2>
 <p>Google sign-in is optional. When you select it, we request only the openid, email and profile permissions. Google returns a signed identity token containing your Google account identifier and available identity claims, including your email address and whether Google has verified it; basic profile claims such as a name or picture may also be included. We verify the token's signature, issuer, audience and the browser's sign-in transaction before using it. If available, an authentication timestamp is used to check recent verification for sensitive account changes.</p>
 <p>We use the Google account identifier to recognize a linked sign-in method under your existing member ID. We use the observed email for the linked-method display and to help the owner review an unmatched login or support request. An email match alone never links an account or grants membership. We do not copy a Google profile name or picture into your store profile. Google data is used only for these sign-in, account linking, security and support functions.</p>
 <p>We do not request or access Gmail messages, contacts, calendars, Google Drive files or Google Workspace content. We do not receive your Google password. We do not use Google user data for advertising, sale, credit decisions, lending, data brokerage or training AI or machine-learning models.</p>
 <h2>Google user data: storage and sharing</h2>
 <p>The application's Cloudflare-hosted database stores the Google provider identifier, observed email, linked member ID, method status and sign-in timestamps. Temporary verification records can contain those identity details while a sign-in or account-change flow is active. Tokens are processed to verify sign-in; Google access, refresh and ID tokens are not saved as reusable credentials or included in application audit records. We do not request offline access.</p>
 <p>Cloudflare processes the stored identity data as our hosting and security provider. The owner keeps encrypted recovery backups that can include these database records. The owner can view linked-method and unmatched-login details to provide account support. These Google identity details are not published to other members or sent to Microsoft. Google handles the sign-in you initiate under its own privacy policy. We do not sell Google user data or disclose it to advertisers, data brokers or unrelated partners. Disclosure may be necessary to comply with law or investigate abuse and protect account access.</p>
 <h2>Other sign-in methods</h2>
 <p>Personal Microsoft sign-in likewise requests openid, email and profile, and stores the provider identifier and observed email for the linked method and account support. It does not request mail, contacts, calendars or files, or receive your Microsoft password. You can use an available passkey or existing snackbar password instead of a provider account.</p>
 <h2>How we use store information</h2>
 <p>We use this information to authenticate approved members, link authorized sign-in methods, fulfill orders, maintain accurate store records, provide community features you choose, support recovery, and prevent abuse. Email or name similarity alone does not establish account ownership. Google account data is used for these user-facing access and support functions, not advertising or model training.</p>
 <h2>Access and service providers</h2>
 <p>Members can access their own account and records, plus community content permitted by the feature's audience and privacy settings. Authorized administrators can access the records needed to operate the store and resolve account issues. New identity authority is managed by the owner.</p>
 <p>Cloudflare hosts the application, database and images and provides security services. Google or Microsoft handles its own sign-in when you select that provider. An owner-controlled encrypted backup is kept for recovery. We do not sell member information or share it with advertising services. We may disclose information where required by law or to address abuse and protect the service.</p>
 <h2>How we protect information</h2>
 <p>HTTPS encrypts information in transit. Server-side access checks restrict member records to authorized users; administrator access has an additional Cloudflare Access and multi-factor verification boundary. Identity administration is restricted to the owner. Recovery archives are encrypted, with the backup key kept separately in the owner's password manager. Passwords are hashed, and passkey private keys remain outside this application.</p>
 <p>Necessary secure, HTTP-only cookies maintain sign-in and bind verification to your browser. Request checks help prevent forged account changes. Linking or removing methods requires fresh proof; account recovery uses independently verified support or private invitations. Secrets and raw authentication tokens are excluded from application audit records. These controls reduce risk but cannot guarantee that every security incident will be prevented.</p>
 <h2>Retention and deletion</h2>
 <p>Google and Microsoft account identifiers and observed emails are retained while needed to maintain linked methods and resolve access or security issues. Removing a method disables it for future sign-in; it does not immediately erase its database record. A revoked identifier can be retained to prevent unsafe reassignment to another member and to investigate past account changes. You may request deletion of these retained details as described below.</p>
 <p>Scheduled cleanup normally removes identifying unmatched-login request details, including the observed email, after 30 days of inactivity; a reduced request record can remain. Ended identity-session metadata is normally removed after 90 days, and identity audit records after 365 days unless placed on an incident hold. Expired temporary verification secrets and proof are cleared after a one-day cleanup window. Cleanup runs periodically in bounded batches, so removal may finish after these thresholds.</p>
 <p>Member and business records are retained for as long as needed to operate the store, reconcile transactions and resolve disputes. Removing Google access or a sign-in method does not erase purchases, payments or other store history. Encrypted backups can contain earlier records until the owner replaces or deletes those archives; live-account deletion does not instantly rewrite existing backups.</p>
 <h2>Your choices and support</h2>
 <p>Open Linked methods after signing in to inspect your methods and sessions, sign out devices, or remove a method when another usable method remains. You can also revoke this app's Google access in your <a href="https://myaccount.google.com/connections">Google Account connections</a>, or revoke Microsoft access through your Microsoft account settings. Revoking provider access does not itself send us a request to delete existing store records.</p>
 <p>To request access, correction, account closure or deletion, including Google user data, email <a href="mailto:snackbar@iyaayasfw.com?subject=Privacy%20request">snackbar@iyaayasfw.com</a> with the subject “Privacy request,” or contact the snackbar administrator through your established unit channel. Identify your member account and the information you want reviewed. Do not send passwords, tokens, recovery codes or identity documents by email. We will verify the requester's authority, review the relevant live records and backups, remove information that is no longer needed, and explain any information retained for accounting, security or unresolved disputes. Deletion requests are reviewed by the owner; there is no automatic delete-account button.</p>
 <h2>Changes and provider policies</h2>
 <p>Google and Microsoft apply their own privacy policies to their services. We will update this page and its effective date when our practices change. If we materially change how we access, use, store or share Google user data, we will notify affected members through the app or an established contact channel before the new use begins and request any additional consent required.</p>
 <nav className="identity-links"><a href="/about">About the app</a><a href="/login">Member sign-in</a></nav>
 </article></main>;}
