'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {csvFile,rosterHeaders,MAX_ROSTER_BYTES,type ImportMode} from '@/lib/identity/roster-format';

type Row={number:number;memberId:string;name:string;email?:string;active:number;status:string;errors:string[];warnings?:string[];changes:string[];grants:{provider:string;raw:string;create:boolean}[]};
type Preview={batch:string;hash:string;rows:Row[]};
export type ImportResults={batch:string;hash:string;applied:number;alreadyApplied:number;conflicts:number;results:{row:number;memberId:string;name:string;email:string;result:string}[]};
type Props={api:(body:Record<string,unknown>)=>Promise<any>;busy:boolean;run:(task:()=>Promise<void>)=>Promise<void>;requestOwner:(payload:Record<string,unknown>)=>Promise<void>;result:ImportResults|null;openMember:(id:string)=>Promise<void>};
export function downloadFile(content:string,filename:string,type='text/csv;charset=utf-8'){
 const url=URL.createObjectURL(new Blob([content],{type})),link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function ImportResultsView({result,openMember,run,busy}:Pick<Props,'result'|'openMember'|'run'|'busy'>){
 if(!result)return null;
 return <section className="identity-block" aria-label="Import results"><h3>Import results</h3><p role="status">{result.applied} applied · {result.alreadyApplied} already applied · {result.conflicts} need review</p><Button variant="outline" onClick={()=>downloadFile(csvFile([['data_row','display_name','email','member_id','result'],...result.results.map(r=>[r.row,r.name,r.email,r.memberId,r.result])]),'iyaayasfw-import-results.csv')}>Download results CSV</Button><div className="identity-table"><table><thead><tr><th>Row</th><th>Member</th><th>Result</th><th>Next step</th></tr></thead><tbody>{result.results.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.name}<small>{r.email}</small></td><td>{r.result}</td><td>{['Applied','Already applied'].includes(r.result)&&<Button disabled={busy} variant="outline" onClick={()=>run(()=>openMember(r.memberId))}>Member &amp; invitation</Button>}</td></tr>)}</tbody></table></div><p>Google preauthorization becomes usable only when the configured Google rollout allows it. Create a private invitation for other sign-in methods. Importing sends no messages.</p></section>;
}
export default function MemberImport({api,busy,run,requestOwner,result,openMember}:Props){
 const [mode,setMode]=useState<ImportMode>('create'),[csv,setCsv]=useState(''),[filename,setFilename]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[selected,setSelected]=useState<number[]>([]);
 const reset=(value:string)=>{setCsv(value);setPreview(null);setSelected([]);};
 const load=async(file:File)=>{if(file.size>MAX_ROSTER_BYTES)throw Error('Choose a CSV file no larger than 64 KB.');if(!/\.csv$/i.test(file.name))throw Error('Save the spreadsheet as CSV UTF-8 (.csv), then upload it.');const value=await file.text();if(value.includes('\uFFFD'))throw Error('The file contains unreadable characters. Save it as CSV UTF-8 in Excel.');reset(value);setFilename(file.name);};
 const ready=preview?.rows.filter(r=>r.status==='Create'||r.status==='Update')||[];
 return <>
  <h3>Member CSV import</h3>
  <div className="identity-choices" role="group" aria-label="Import workflow">{(['create','update'] as const).map(m=><Button key={m} disabled={busy} variant={mode===m?'default':'outline'} aria-pressed={mode===m} onClick={()=>{setMode(m);reset('');setFilename('');}}>{m==='create'?'Import new members':'Update existing members'}</Button>)}</div>
  <p>{mode==='create'?'Create up to 100 new members. Existing accounts are never overwritten.':'Update up to 100 existing members using their member IDs. Blank cells preserve existing values.'}</p>
  <ol className="identity-import-steps"><li>Download the template and open it in Excel.</li><li>Enter one member per row and save as <strong>CSV UTF-8</strong>.</li><li>Upload, review each row, then verify and confirm the selected changes.</li></ol>
  <Button variant="outline" disabled={busy} onClick={()=>run(async()=>{const template=await api({action:'importTemplate',mode});downloadFile(template.csv,template.filename||'iyaayasfw-existing-members-template.csv');})}>Download CSV template</Button>
  <details className="identity-import-help"><summary>Columns and example</summary><dl>{(mode==='create'?[
   ['display_name','Required. The member’s name, up to 80 characters.'],['email','Required. Primary member email; does not automatically grant Google sign-in.'],['contact_email','Optional separate contact address.'],['google_bootstrap_email','Optional exact Google sign-in address to preauthorize. Leave blank for invitation-only onboarding.'],['access_enabled','Required. TRUE or FALSE. Use TRUE when preauthorizing Google.'],
  ]:[['member_id','Required. The existing member ID supplied in the template.'],['display_name','Optional replacement name.'],['contact_email','Optional replacement contact email, with no login authority.'],['google_bootstrap_email','Optional Google first-sign-in preauthorization.'],['microsoft_bootstrap_email','Legacy column. Leave blank; use a private invitation for Microsoft.'],['access_enabled','TRUE/FALSE to change access, or blank to preserve it.']]).map(([name,description])=><div key={name}><dt><code>{name}</code></dt><dd>{description}</dd></div>)}</dl><code className="identity-template">{rosterHeaders(mode).join(',')}<br/>{mode==='create'?'Example Member,member@example.com,,member@gmail.com,TRUE':'existing-member-id,Updated Name,,,,TRUE'}</code><p>Examples are not included in the downloaded file. Google must verify Gmail or managed Workspace addresses; other Google-account addresses use invitations. New members start with $0 debt and credit, a $30 tab limit, snacks and gear access, and community posting enabled. No administrator rights are imported.</p></details>
  <div className="identity-upload" onDragOver={e=>{e.preventDefault();}} onDrop={e=>{e.preventDefault();if(busy)return;if(e.dataTransfer.files.length!==1){void run(async()=>{throw Error('Upload one CSV file at a time.');});return;}void run(()=>load(e.dataTransfer.files[0]));}}><label className="field">Upload CSV file or drop it here<Input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(file)void run(()=>load(file));}}/></label><p className="fine">{filename||'CSV UTF-8 · up to 100 members · 64 KB maximum'}</p></div>
  <details><summary>Paste or inspect CSV text</summary><label className="field">CSV rows<textarea rows={6} value={csv} disabled={busy} onChange={e=>{reset(e.target.value);setFilename('Pasted CSV');}} maxLength={MAX_ROSTER_BYTES}/></label></details>
  <Button disabled={busy||!csv} variant="outline" onClick={()=>run(async()=>{const p=await api({action:'importPreview',mode,csv}) as Preview;setPreview(p);setSelected(p.rows.filter(r=>r.status==='Create'||r.status==='Update').map(r=>r.number));})}>Preview {mode==='create'?'new members':'changes'}</Button>
  {preview&&<><p role="status">{ready.length} ready · {preview.rows.filter(r=>r.status==='Exists'||r.status==='Unchanged').length} skipped · {preview.rows.filter(r=>r.errors.length).length} need correction. No members have been changed.</p><div className="identity-choices"><Button variant="ghost" disabled={busy||!ready.length} onClick={()=>setSelected(ready.map(r=>r.number))}>Select ready rows</Button><Button variant="ghost" disabled={busy} onClick={()=>setSelected([])}>Clear selection</Button><Button variant="outline" onClick={()=>downloadFile(csvFile([['data_row','display_name','email','result','details'],...preview.rows.map(r=>[r.number,r.name,r.email||'',r.status,[...r.errors,...(r.warnings||[]),...r.changes].join('; ')])]),'iyaayasfw-import-preview.csv')}>Download review CSV</Button></div>
   <p className="fine">Scroll the table sideways to see all columns on a small screen.</p><div className="identity-table"><table><thead><tr><th>Apply</th><th>Row</th><th>Member</th><th>Result</th><th>Details</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.number}><td><input aria-label={'Apply row '+r.number} type="checkbox" disabled={busy||!['Create','Update'].includes(r.status)} checked={selected.includes(r.number)} onChange={e=>setSelected(v=>e.target.checked?[...v,r.number]:v.filter(n=>n!==r.number))}/></td><td>{r.number}</td><td>{r.name}<small>{r.email||r.memberId}</small></td><td>{r.status==='Create'?'Ready to create':r.status==='Exists'?'Already exists':r.status==='Conflict'?'Needs correction':r.status}</td><td>{r.errors.length?r.errors.join(' '):r.changes.join(' ')||'No changes'}{r.grants.map(g=><small key={g.provider}>{g.provider}: {g.raw}{g.create?' (new preauthorization)':' (existing reservation preserved)'}</small>)}{r.warnings?.map(w=><p className="fine" key={w}>{w}</p>)}</td></tr>)}</tbody></table></div>
   <Button disabled={busy||!selected.length} onClick={()=>run(()=>requestOwner({operation:'importCommit',batch:preview.batch,hash:preview.hash,rows:selected}))}>Verify &amp; {mode==='create'?'create':'update'} {selected.length} selected {selected.length===1?'member':'members'}</Button><p className="fine">Review warnings before continuing. The preview expires after 10 minutes. Each selected row is applied completely or left unchanged; results identify any conflicts.</p>
  </>}
  <ImportResultsView result={result} openMember={openMember} run={run} busy={busy}/>
 </>;
}
