'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Package,ShoppingBag} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {gearKey,loadCart,saveCart,cartLines} from '@/lib/pilot/cart';
type Row=Record<string,any>;
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100);
export default function ProductPage({id}:{id:string}){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[option,setOption]=useState(''),[text,setText]=useState(''),[qty,setQty]=useState(1),[selectedImage,setSelectedImage]=useState(0),[added,setAdded]=useState(false);
 useEffect(()=>{fetch('/api/pilot',{cache:'no-store'}).then(async r=>{if(r.status===401){window.location.replace('/login?next='+encodeURIComponent('/products/'+id));return}const j=await r.json() as Row;if(!r.ok)throw Error(j.error);setData(j)}).catch(e=>setError(e.message))},[id]);
 const p=data?.products.find((p:Row)=>p.id===id&&p.category==='Gear'&&!p.archived&&p.active),variants=p?.variants.filter((v:Row)=>v.active)||[],v=variants.find((v:Row)=>v.id===option),price=v?.price??p?.price,preorder=v?v.preorder:p?.preorder,stock=v?v.stock:p?.stock,images=[...new Set([p?.image,...(p?.images||[])].filter(Boolean))] as string[],available=p&&data?.settings.enabled&&(!p.option_required||v)&&price>0&&p.tax_bp!==null&&(preorder||stock>=qty);
 function add(e:React.FormEvent){e.preventDefault();setError('');if(!available)return;const cart=loadCart();try{if(sessionStorage.getItem('supply-pending'))throw Error('Resolve the pending action in your bag before adding another item.');if(p.personalization_required&&!text.trim())throw Error('Enter '+p.personalization_label+'.');const key=gearKey(id,option,text.trim(),price),quantity=(cart[key]||0)+qty;if(quantity>30)throw Error('Limit each option to 30 per purchase.');const used=cartLines(cart,data!.products).filter(i=>i.stockKey===(option||id)).reduce((s,i)=>s+i.qty,0);if(!preorder&&used+qty>stock)throw Error('Your bag already contains the available stock.');saveCart({...cart,[key]:quantity});setAdded(true)}catch(e){setError(e instanceof Error?e.message:'Try again.')}}
 return <div className="app product-page"><header className="topbar"><a className="brand" href="/?view=gear"><span className="brand-mark">I</span><span>IYAAYASFW<span className="brand-sub">Unit Supply</span></span></a><Button asChild variant="outline"><a href="/?view=gear"><ShoppingBag size={17}/>Your bag</a></Button></header><main><Button asChild variant="ghost"><a href="/?view=gear"><ArrowLeft size={16}/>Back to unit gear</a></Button>{!data?<p role="status">{error||'Loading product…'}</p>:!p?<section className="panel"><h1>Product unavailable</h1><p>This item is not available for your account.</p></section>:<div className="product-detail-layout"><section className="product-gallery" aria-label="Product images"><div className="gallery-main">{images.length?<img src={images[selectedImage]||images[0]} alt={p.name+' · image '+(selectedImage+1)}/>:<Package size={64}/>}</div>{images.length>1?<div className="gallery-thumbs">{images.map((image,i)=><button type="button" key={image} aria-label={'View product image '+(i+1)} aria-pressed={selectedImage===i} onClick={()=>setSelectedImage(i)}><img src={image} alt=""/></button>)}</div>:null}</section><section className="product-detail-copy"><span className="eyebrow">Unit gear · Pickup only</span><h1>{p.name}</h1><p className="product-subtitle">{p.detail}</p><p className="detail-price">{price==null?'Price unavailable':money(price)}{variants.length&&!v?' base price':''}</p><p className="fine">Includes configured tax.</p><div className="product-description">{p.description||'Choose your item below. Your order will be available for pickup through the unit store.'}</div>
 <form onSubmit={add}><fieldset disabled={!data.settings.enabled}><div className="form-grid">{variants.length?<label className="field"><span>Size / color</span><NativeSelect value={option} onChange={e=>{setOption(e.target.value);setAdded(false)}} required><option value="">Choose an option</option>{variants.map((v:Row)=><option key={v.id} value={v.id}>{v.label} · {(v.price??p.price)==null?'Price unavailable':money(v.price??p.price)}{v.preorder?' · Preorder':v.stock?'':' · Out of stock'}</option>)}</NativeSelect></label>:null}<label className="field"><span>Quantity</span><Input type="number" min={1} max={preorder?30:Math.min(30,stock||1)} value={qty} required onChange={e=>{setQty(Number(e.target.value));setAdded(false)}}/></label></div>{p.personalization_label?<label className="field"><span>{p.personalization_label}{p.personalization_required?' *':' (optional)'}</span><Input value={text} onChange={e=>{setText(e.target.value);setAdded(false)}} required={!!p.personalization_required} maxLength={p.personalization_max} placeholder={p.personalization_label==='Last name'?'Enter the name exactly as it should appear':''}/><small>Check spelling and capitalization. This text is saved with your order.</small></label>:null}<p className="notice">{preorder?'Preorder · Pay before the group order is placed. Check My account for pickup updates.':stock>0?'In stock · Check My account for pickup status.':'Currently out of stock.'}{p.pickup_note?' '+p.pickup_note:''}</p>{p.option_required&&!variants.length?<p className="notice warning">Product options are currently unavailable.</p>:null}{!data.settings.enabled?<p className="notice warning">The shop is temporarily paused.</p>:null}{error?<p className="notice error" role="alert">{error}</p>:null}{added?<p className="notice" role="status">Added to your bag.</p>:null}<div className="inline-actions"><Button type="submit" disabled={!available}><ShoppingBag size={17}/>Add to bag{available?' · '+money(price*qty):''}</Button><Button variant="outline" asChild><a href="/?view=gear">View bag & checkout</a></Button></div></fieldset></form></section></div>}</main></div>
}
