type Row=Record<string,any>;
export const CART_KEY='supply-bag-v2';
export function loadCart():Record<string,number>{try{const value=JSON.parse(sessionStorage.getItem(CART_KEY)||'{}');return Object.fromEntries(Object.entries(value).filter(([key,qty])=>key.length<800&&Number.isSafeInteger(qty)&&Number(qty)>0&&Number(qty)<=30)) as Record<string,number>}catch{return{}}}
export function saveCart(cart:Record<string,number>){try{sessionStorage.setItem(CART_KEY,JSON.stringify(cart))}catch{}}
export function gearKey(id:string,variantId:string,personalization:string,price:number){return 'gear:'+encodeURIComponent(JSON.stringify({id,variantId,personalization,price}))}
export function cartLines(cart:Record<string,number>,products:Row[]):Row[]{return Object.entries(cart).flatMap(([key,qty])=>{let spec:Row={id:key};try{if(key.startsWith('gear:'))spec=JSON.parse(decodeURIComponent(key.slice(5)))}catch{return[]};const p=products.find(p=>p.id===spec.id);if(!p)return[];const v=spec.variantId?p.variants?.find((v:Row)=>v.id===spec.variantId):null;return[{...p,key,qty,variantId:spec.variantId||'',variantLabel:v?.label||'',personalization:spec.personalization||'',price:spec.price??p.price,currentPrice:v?.price??p.price,stock:v?v.stock:p.stock,preorder:v?v.preorder:p.preorder,active:p.active&&(!spec.variantId||!!v?.active),missingOption:!!spec.variantId&&!v,stockKey:spec.variantId||p.id}]})}
export function cartValid(lines:Row[]){return !!lines.length&&lines.every(p=>!p.archived&&p.active&&p.price>0&&p.price===p.currentPrice&&p.tax_bp!==null&&!p.missingOption&&(p.preorder||lines.filter(x=>x.stockKey===p.stockKey).reduce((n,x)=>n+x.qty,0)<=p.stock))}
export function productAvailability(p:Row){if(p.archived)return 'Archived';if(!p.active)return 'Hidden';const variants=p.variants||[];if(p.option_required||variants.length){if(p.tax_bp===null)return 'Needs pricing';if(variants.some((v:Row)=>v.active&&(v.price??p.price)>0&&(v.preorder||v.stock>0)))return 'Available';return 'Options unavailable'}if(p.price===null||p.tax_bp===null)return 'Needs pricing';if(p.preorder)return 'Preorder';return p.stock>0?'Available':'Out of stock'}
export function productReady(p:Row){return ['Available','Preorder'].includes(productAvailability(p))}
