import {type DB,type Row,fail,int,str,uid,reqId,first,rows,stmt,audit,guard,hash,batchAtomic} from './core';
import {accessFor,canShop} from './access';
export async function placeOrder(db:DB,m:Row,b:Row,settings:Row){
 const actor=m.id,id=reqId(b.id),method=str(b.method,20);if(!['cash','cashapp','tab','credit'].includes(method))fail('Choose an available payment method.');
 const payer=m.name;if(!Array.isArray(b.items)||!b.items.length||b.items.length>30)fail('Select between 1 and 30 products.');
 const items=b.items.map((v:Row)=>({id:str(v.id,80),qty:int(v.qty,1,30),price:int(v.price,1,100000),...(v.variantId?{variantId:str(v.variantId,80)}:{}),...(v.personalization?{personalization:str(v.personalization,80)}:{})})).sort((a:Row,c:Row)=>a.id.localeCompare(c.id)||JSON.stringify(a).localeCompare(JSON.stringify(c)));
 const key=(i:Row)=>JSON.stringify([i.id,i.variantId||'',i.personalization||'']);if(new Set(items.map(key)).size!==items.length)fail('Combine duplicate products and options in the basket.');
 const fp=await hash({actor,payer,method,items});const duplicate=async()=>{const old=await first(db,'SELECT * FROM orders WHERE id=?',id);if(old&&old.fingerprint!==fp)fail('This request identifier has already been used.',409);return old};const old=await duplicate();if(old)return{order:old,replayed:true};
 if(!settings.enabled)fail('The shop is paused. An administrator can reopen it from Shop controls.');if(method==='cashapp'&&!settings.cashtag)fail('Cash App is not configured yet.');
 const access=await accessFor(db,m as any),ps=await rows(db,'SELECT p.*,d.archived,d.personalization_label,d.personalization_required,d.personalization_max FROM products p LEFT JOIN product_details d ON d.product_id=p.id'),variants=await rows(db,'SELECT * FROM product_variants');let total=0,tax=0,cost:number|null=0;
 const quantities=new Map<string,number>();
 const lines=items.map((item:Row):Row=>{
  const p=ps.find(p=>p.id===item.id);if(!p||!p.active||p.archived||p.tax_bp===null)fail('One of these products is not ready for sale.');if(!canShop(m as any,access,p.category))fail('Your account cannot purchase from this shop.',403);if(p.category==='Gear'&&method==='tab')fail('Unit gear must be paid upfront.');
  const options=variants.filter(v=>v.product_id===p.id),variant=item.variantId?options.find(v=>v.id===item.variantId&&v.active):null;if(item.variantId&&!variant)fail('This product option is unavailable.');if(options.length&&!variant)fail('Select an available size or color on the product page.');
  if(item.personalization&&(!p.personalization_label||p.category!=='Gear'))fail('This product does not accept personalization.');if(p.personalization_required&&!item.personalization)fail('Enter '+(p.personalization_label||'personalization')+' for '+p.name+'.');if((item.personalization||'').length>(p.personalization_max||30)||/[\x00-\x1f\x7f]/.test(item.personalization||''))fail('Review the personalization text for '+p.name+'.');
  const price=variant?.price??p.price,unitCost=variant?.cost??p.cost,preorder=variant?variant.preorder:p.preorder,stock=variant?variant.stock:p.stock;
  if(price===null||price!==item.price)fail('A price changed. Refresh your basket before checking out.',409);
  const stockKey=variant?'v:'+variant.id:'p:'+p.id,qty=(quantities.get(stockKey)||0)+item.qty;quantities.set(stockKey,qty);if(!preorder&&stock<qty)fail(`${p.name} has insufficient stock.`,409);
  total+=price*item.qty;tax+=Math.round(price*item.qty*p.tax_bp/(10000+p.tax_bp));cost=cost===null||unitCost===null?null:cost+unitCost*item.qty;
  return{...p,price,cost:unitCost,preorder,qty:item.qty,variant,personalization:item.personalization||''};
 });
 if(total>50000)fail('Keep each purchase under $500.');
 const time=Date.now(),code='SB-'+id.slice(0,8).toUpperCase(),status=method==='tab'?'tab':method==='credit'?'paid':'pending';
 // JSON batches keep larger group orders within the Free plan's query budget.
 const packet=JSON.stringify(lines.map(p=>({...p,itemId:uid(),variantId:p.variant?.id||'',variantVersion:p.variant?.version??0,variantLabel:p.variant?.label||'',stockQty:quantities.get(p.variant?'v:'+p.variant.id:'p:'+p.id)})));
 const statements=[guard(db,"EXISTS(SELECT 1 FROM settings WHERE id='main' AND enabled=1)"),guard(db,"EXISTS(SELECT 1 FROM members m LEFT JOIN member_access a ON a.member_id=m.id WHERE m.id=? AND m.active=1 AND (?=0 OR m.role='admin' OR COALESCE(a.snacks,1)=1) AND (?=0 OR m.role='admin' OR COALESCE(a.gear,1)=1))",actor,lines.some(p=>p.category!=='Gear')?1:0,lines.some(p=>p.category==='Gear')?1:0),
 guard(db,`NOT EXISTS(SELECT 1 FROM json_each(?) j LEFT JOIN products p ON p.id=json_extract(j.value,'$.id') LEFT JOIN product_details d ON d.product_id=p.id WHERE p.id IS NULL OR p.active<>1 OR p.version<>json_extract(j.value,'$.version') OR COALESCE(d.archived,0)<>0 OR (json_extract(j.value,'$.variantId')='' AND (EXISTS(SELECT 1 FROM product_variants v WHERE v.product_id=p.id) OR (p.preorder=0 AND p.stock<json_extract(j.value,'$.stockQty')))))`,packet),
 guard(db,`NOT EXISTS(SELECT 1 FROM json_each(?) j LEFT JOIN product_variants v ON v.id=json_extract(j.value,'$.variantId') AND v.product_id=json_extract(j.value,'$.id') WHERE json_extract(j.value,'$.variantId')<>'' AND (v.id IS NULL OR v.active<>1 OR v.version<>json_extract(j.value,'$.variantVersion') OR (v.preorder=0 AND v.stock<json_extract(j.value,'$.stockQty'))))`,packet),
 stmt(db,`UPDATE products SET stock=stock-(SELECT SUM(json_extract(value,'$.qty')) FROM json_each(?) WHERE json_extract(value,'$.id')=products.id AND json_extract(value,'$.variantId')='' AND json_extract(value,'$.preorder')=0) WHERE id IN(SELECT json_extract(value,'$.id') FROM json_each(?) WHERE json_extract(value,'$.variantId')='' AND json_extract(value,'$.preorder')=0)`,packet,packet),
 stmt(db,`UPDATE product_variants SET stock=stock-(SELECT SUM(json_extract(value,'$.qty')) FROM json_each(?) WHERE json_extract(value,'$.variantId')=product_variants.id AND json_extract(value,'$.preorder')=0) WHERE id IN(SELECT json_extract(value,'$.variantId') FROM json_each(?) WHERE json_extract(value,'$.variantId')<>'' AND json_extract(value,'$.preorder')=0)`,packet,packet)];
 if(method==='tab')statements.push(guard(db,'EXISTS(SELECT 1 FROM members WHERE id=? AND active=1 AND debt+?<=tab_limit)',actor,total),stmt(db,'UPDATE members SET due_since=CASE WHEN debt=0 THEN ? ELSE due_since END,debt=debt+? WHERE id=?',time,total,actor));
 if(method==='credit')statements.push(guard(db,'EXISTS(SELECT 1 FROM members WHERE id=? AND active=1 AND credit>=?)',actor,total),stmt(db,'UPDATE members SET credit=credit-? WHERE id=?',total,actor));
 statements.push(stmt(db,'INSERT INTO orders(id,code,fingerprint,member_id,payer,method,total,tax,cost,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,code,fp,actor,payer,method,total,tax,cost,status,time));
 statements.push(stmt(db,`INSERT INTO order_items(id,order_id,product_id,name,qty,price,cost,tax_bp,preorder) SELECT json_extract(value,'$.itemId'),?,json_extract(value,'$.id'),json_extract(value,'$.name'),json_extract(value,'$.qty'),json_extract(value,'$.price'),json_extract(value,'$.cost'),json_extract(value,'$.tax_bp'),json_extract(value,'$.preorder') FROM json_each(?)`,id,packet),stmt(db,`INSERT INTO order_item_details(item_id,variant_id,variant_label,personalization,fulfillment,updated_at) SELECT json_extract(value,'$.itemId'),NULLIF(json_extract(value,'$.variantId'),''),json_extract(value,'$.variantLabel'),json_extract(value,'$.personalization'),CASE WHEN json_extract(value,'$.preorder')=1 THEN 'awaiting_stock' ELSE 'ready' END,? FROM json_each(?) WHERE json_extract(value,'$.category')='Gear'`,time,packet));
 if(status==='pending')statements.push(stmt(db,"INSERT INTO payments(id,fingerprint,order_id,member_id,purpose,method,amount,created_at) VALUES(?,?,?,?,'purchase',?,?,?)",id,fp,id,actor,method,total,time));
 statements.push(audit(db,actor,'consumption',id,{items,total,method}));try{await batchAtomic(db,statements)}catch(e){const retry=await duplicate();if(retry)return{order:retry,replayed:true};throw e}
 return{order:await first(db,'SELECT * FROM orders WHERE id=?',id)};
}
