import {randomBytes} from 'node:crypto';
import {digest} from './password';
export const COOKIE='__Host-supply-session';
export const SESSION_SECONDS=34560000; // 400 days, renewed by authenticated API visits.
export function sessionCookie(token:string,maxAge=SESSION_SECONDS){return `${COOKIE}=${token}; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=${maxAge}`}
export function tokenFromCookie(cookie:string|null){const value=(cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);return value&&/^[a-f0-9]{64}$/.test(value)?value:null}
export async function sessionUser(db:D1Database,cookie:string|null){const token=tokenFromCookie(cookie);if(!token)return null;const row=await db.prepare('SELECT m.id,m.email,m.name,m.role,m.user_id,s.token_hash FROM auth_sessions s JOIN members m ON m.id=s.member_id JOIN auth_credentials c ON c.member_id=m.id WHERE s.token_hash=? AND s.expires_at>? AND m.active=1').bind(digest(token),Date.now()).first<{id:string;email:string;name:string;role:string;user_id:string|null;token_hash:string}>();return row?{memberId:row.id,userId:row.user_id||'member:'+row.id,email:row.email,displayName:row.name,role:row.role,tokenHash:row.token_hash}:null}
export async function issueSession(db:D1Database,memberId:string,credentialHash:string){const token=randomBytes(32).toString('hex');const result=await db.prepare('INSERT INTO auth_sessions(token_hash,member_id,created_at,expires_at) SELECT ?,m.id,?,? FROM members m JOIN auth_credentials c ON c.member_id=m.id WHERE m.id=? AND m.active=1 AND c.password_hash=?').bind(digest(token),Date.now(),Date.now()+SESSION_SECONDS*1000,memberId,credentialHash).run();if(!result.meta.changes)return null;return token}
export async function renewSession(db:D1Database,cookie:string|null){const token=tokenFromCookie(cookie);if(!token)return null;const changed=await db.prepare('UPDATE auth_sessions SET expires_at=? WHERE token_hash=? AND expires_at>? AND EXISTS(SELECT 1 FROM members WHERE id=auth_sessions.member_id AND active=1)').bind(Date.now()+SESSION_SECONDS*1000,digest(token),Date.now()).run();return changed.meta.changes?sessionCookie(token):null}
export async function revokeSession(db:D1Database,cookie:string|null){const token=tokenFromCookie(cookie);if(token)await db.prepare('DELETE FROM auth_sessions WHERE token_hash=?').bind(digest(token)).run()}
export async function rateLimit(db:D1Database,key:string,limit:number,windowMs:number){const now=Date.now(),bucket=Math.floor(now/windowMs),id=digest(key)+':'+bucket;const row=await db.prepare('INSERT INTO auth_limits(id,count,expires_at) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count').bind(id,(bucket+1)*windowMs).first<{count:number}>();return !!row&&row.count<=limit}
